### ISSUE TITLE
Installation with pip, missing nose package to run test

### ISSUE THREAD

**Issue by ghaessig** [brian-team/brian2#1031]
After a fresh install with pip under python 2.7, seems like the 'nose' python package is missing in order to run 'brian2.test()'

Installing it manually fixes the error. Maybe add it to the dependencies list ?

**Comment by mstimberg** [comment]
I don't think we need `nose` as a dependency by default, since users don't normally have to run the test suite. Also, the documentation and error message quite clearly mentions what you need to do if you *do* want to run it. This approach is compatible with what other packages do, e.g. `numpy` does not depend on `pytest` either (side note: in the long run, we want to replace `nose` by `pytest` as well).

However, I *did* notice a bug: we define the "extra target" `test` in Brian's `setup.py`, i.e. you should be able to install Brian with everything needed for testing by calling `pip install brian2[test]`; unfortunately, this depends on the non-existing package `nosetests` instead of `nose`... I'll fix this as part of PR #1029.
