### ISSUE TITLE
equality in custom events

### ISSUE THREAD

**Issue by kevincuallado** [brian-team/brian2#1035]
Wanting to create a reset-able clock in addition to the general simulation clock and have custom events associated with it, I used the following code to test my idea:
```
from brian2 import (NeuronGroup, Network, StateMonitor, EventMonitor, ms)

eqs = """
t_rel : second
counter : 1
"""
n = NeuronGroup(4, eqs, dt=1*ms, events={"potentiate": 't_rel == 20*ms'})
n.run_on_event('potentiate', 'counter += 1')
t_mon = StateMonitor(n, "t_rel", record=True)
pot_mon = EventMonitor(n, "potentiate", record=True)
count_mon = StateMonitor(n, 'counter', record=True)
n.counter = 0
n.t_rel = -1*ms
n.run_regularly('t_rel += 1*ms', dt=1*ms)
net = Network(
    n, t_mon, pot_mon, count_mon
)
net.run(30*ms)
n.t_rel = -1*ms
net.run(30*ms)

print(pot_mon.it)
print(t_mon.t_rel[0])
print(count_mon.counter[0])
```
Excepted behavior would be to have it fire the event twice; however, both pot_on and count_mon present no sign of the `potentiate` event ; however, when the event condition is replaced as such:
```
n = NeuronGroup(4, eqs, dt=1*ms, events={"potentiate": 't_rel >= 20*ms and t_rel < 21*ms'})
```
The event fires twice as expected.
I seem to understand there should be no difference between the two conditions, considering t_rel is incremented by 1*ms. Could it be a bug in the management of custom event conditions?

Version is 2.2.0

Edit:
For testing purposes, I removed the dt argument of the neurongroup, so that it can measure t_rel 10 times before changing its value, and the problem still persists.

**Comment by mstimberg** [comment]
Hi. This is not an issue in Brian as such, but a general property of [floating-point arithmetics](https://en.wikipedia.org/wiki/Floating-point_arithmetic). You should never compare floating point numbers for equality (and quantities in Brian are simple floating point numbers "under the hood"). E.g. the following, neither using Brian nor units, but simply storing time in seconds, does fail as well:
```Python
x = 0.0
for _ in range(20):
    x += 0.001
print(x == 0.020)
```
will give `False` because `x` is not `0.02` but `0.02000000000000001`...

There are several solutions (your "range comparison" is one of them), one of the following is probably the best:
1. Use an integer counter instead of a time in seconds, i.e. define `t_rel` as `t_rel : integer` and use `t_rel += 1` for the `run_regularly` and `t_rel == 20` for the check. If you need a time for other calculations, you can simply use `t_rel * 1*ms`. (This is what Brian uses internally for the time `t`)
2. Make use of Brian's [timestep function](https://brian2.readthedocs.io/en/stable/advanced/functions.html#default-functions) that gives the time step into which a time quantity falls, dealing with rounding issues. Your check would compare `timestep(t_rel, dt) == timestep(20*ms, dt)`. (This is what Brian uses to check refractoriness conditions).
