### ISSUE TITLE
Synapse generator syntax sometimes incorrect with postsynaptic condition

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#1037]
The following code tries to connect to a neuron with target index 10 (which does not exist), triggered by a `rand()` condition in the `if` part. It does not matter whether this is actually doing anything, e.g. `rand() <= 1.0` triggers the same problem.
```Python
source = NeuronGroup(10, '')
target = NeuronGroup(10, '')
syn = Synapses(source, target)
syn.connect(j='k for k in range(i, i+5) if i < 5 and rand() < 0.5')
```
Of course users should rather use `sample(i, i+5, p=0.5)` here, but 1) it should still work and 2) it might be a symptom of a larger issue.

**Comment by mstimberg** [comment]
Ok, the `rand()` was actually only a very specific example of a more general issue. The error is triggered if 1) the generator part (without applying the condition) generates values outside of the valid range and 2) the condition has a post-synaptic component (`rand()` has to be checked for every target and is therefore "postsynaptic" as well). In that case, the range check will be done *before* the condition is applied, therefore triggering for targets that will be later removed by the condition (in the above example, all the targets for `i>=5`).

I think we can simply move the check after the application of the post-synaptic condition.

**Comment by mstimberg** [comment]
Actually, this is somewhat more complicated than I thought, I now think we *should* handle this differently for `rand()` (and comparable functions).

The main issue is what should we expect for a generator like:
`syn.connect(j='k for k in range(i, i+5) if i < 5 and variable_post > 0')`?
If we check the condition for all potential targets generated by the iterator, we'll index into `variable_post` with an illegal index. I don't think we want to make our code much more complicated by, say, separating the condition into pre-synaptic and post-synaptic elements and then checking `i < 5` first, etc. So, the best solution here would probably be to keep our existing error about illegal targets *before* checking the post-synaptic condition, but improve the error message.

We'd then have to make a difference between a situation where we actually index post-synaptically (as in the example above) and a situation where we use something like `rand()` -- in that case, generating random numbers for non-existing targets wouldn't be a problem.

**Comment by thesamovar** [comment]
Interesting. One option would be to change ``rand()`` so that it has a different index (not tied to ``j`` but rather directly to ``k`` in this example). That's logical. Then we can analyse ``cond`` and determine whether it indexes pre, post and/or the range variable, and raise an error only if there is a post dependency and an out-of-range j value. That's quite a bit of work but maybe it's the most logically coherent thing to do.

The other option is that we just consider that ``cond`` is always ``cond(i, j)`` and may have post-synaptic dependency and therefore raise an error whenever an out of range j value is encountered. It's easy enough to fix the problem by just adding ``skip_if_invalid=True``.

I'm OK with either of these solutions, but as you noted just moving the condition evaluation part around in the code doesn't seem to work as a solution.

I also don't think we should try to break the condition down into pre and post parts and do any short circuiting. That's just too complex to support. So the ``if i < 5 and variable_post > 0`` example should lead to an error (even though it's possible to evaluate it in such a way as to make it OK).

Have I missed something?

Another option by the way is to add the option of ``for i in range(5)`` into the generator. Can this not be done with subgroups though?

**Comment by mstimberg** [comment]
> Interesting. One option would be to change `rand()` so that it has a different index (not tied to `j` but rather directly to `k` in this example). That's logical. Then we can analyse `cond` and determine whether it indexes pre, post and/or the range variable, and raise an error only if there is a post dependency and an out-of-range j value. That's quite a bit of work but maybe it's the most logically coherent thing to do.

I think we have to do a bit more than that: if there is a post-dependency and out-of-range j value, we want to raise an error *before* the check of the condition, but in the other case (e.g. if the condition is just `rand() < 0.5`) we want to make a check *after* applying the condition.

Hmm, I guess this will be a bit verbose but not *too* difficult?

> The other option is that we just consider that `cond` is always `cond(i, j)` and may have post-synaptic dependency and therefore raise an error whenever an out of range j value is encountered. It's easy enough to fix the problem by just adding `skip_if_invalid=True`.

I think this would be a bit ugly (and backwards incompatible), I think everything that creates valid `j` values (without accessing invalid array elements during the check) in the end should work without `skip_if_invalid`.

> Another option by the way is to add the option of `for i in range(5)` into the generator. Can this not be done with subgroups though?

I don't think we need this, this would only make the syntax even more complicated. As you say, you can do this with subgroups.

**Comment by thesamovar** [comment]
Would the "always consider ``cond=cond(i,j)``" option be backwards-incompatible? What's an example that currently works that wouldn't work with that assumption? Isn't the current issue an example showing it doesn't currently work? In any case, I'm very happy to support the more general syntax by having two checks if it's not too difficult - it would be a minor but nice to have feature.

**Comment by mstimberg** [comment]
> Would the "always consider `cond=cond(i,j)`" option be backwards-incompatible? What's an example that currently works that wouldn't work with that assumption?

If I understood correctly, the `cond=cond(i,j)` would not work for
```Python
syn.connect(j='k for k in range(i, i+5) if i < 5')
```
which currently works, because the condition is identified as pre-synaptic and therefore evaluated early.

**Comment by thesamovar** [comment]
Ah right, yes. OK, so we go with the slightly complicated solution?

**Comment by mstimberg** [comment]
I'll give it a try tomorrow and see whether I run into any unexpected difficulties.
