### ISSUE TITLE
Rename 'reset'?

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#106]
The name 'reset' is actually slightly misleading in the sense that we will often use it not just as a reset but as a general spike-triggered event code to do things like modify adaptation variables. Perhaps a better name that reflects that? I can't immediately think of a good idea.

**Comment by romainbrette** [comment]
I think we should first see a few examples.

**Comment by thesamovar** [comment]
My thoughts:
- I'm happier with threshold than reset
- I still think there's a good case to leave it as it is to not break backwards compatbility
- I think on_spike is potentially confusing because it suggests that you'll be defining what happens when a spike occurs, which sounds like it would include the synaptic behaviour to me
- How about ``spike_if='v>1', after_spike='v=0'``?

**Comment by thesamovar** [comment]
Or maybe ``spike_when='v>1'``?

**Comment by romainbrette** [comment]
spike_when and after_spike are not bad!

There's indeed the issue of backwards compatibility. Perhaps we could 
issue a "Deprecated" warning when using threshold/reset.

**Comment by mstimberg** [comment]
Sorry, to be the annoying guy here, but I think that `spike_when` and `after_spike` are one step forward but also one step back at the same time: since they have `spike` in the name, they will look odd for models where it is not actually about a spike but some other general "regime change". For example, in our ongoing modeling work for astrocytes we use the threshold/reset mechanism to release gliotransmitters when the Calcium levels crosses a threshold. I feel that `threshold` is a more general term here (even though `threshold_condition` would be more appropriate, but it's a bit long). But I also agree that `reset` is not appropriate in many contexts (including the astrocyte modeling) though.

Something that we should keep in mind is that we want to generalize to other event types in the future (#105). Will we do this with a separate `events` keyword arguments or generalize `threshold`/`reset`, i.e. allow to pass dictionaries to them?

Whatever we decide, `threshold`/`reset` are very central in almost every Brian model, so we should definitely have a transition period where they still work but lead to a deprecation warning (and later have a helpful error message)

**Comment by romainbrette** [comment]
event_when and after_event would be more general. Possibly more obscure 
too though.

**Comment by thesamovar** [comment]
We did decide to do more general types of events, so my suggestion would be to use ``spike_when``, ``after_spike`` for the spike event, and have a more general syntax for different types of events (maybe ``events=...``). At the moment, we're using the spike event for non-spike events as a sort of hack, but that should disappear if we allow for other types of events.

**Comment by mstimberg** [comment]
I think it would be good to do the changes together in this case, i.e. rename threshold/reset and add general events. It should actually be straightforward to do so (the `threshold` and `reset` templates would get a keyword argument for the event name and for each event we'd had an `eventspace` array exactly like `spikespace`), and it would be a nice generalization.
In the astrocyte example, we could then use this event mechanism instead of threshold/reset, so that makes the problem with the wording go away. It would be nice if we had an example where we actually need this mechanism, though, i.e. one where we have spikes but also an additional discrete event. 

One more thing: I guess we should rename the scheduling slots `thresholds` and `resets` as well? There's also the name of the templates, but that's less important since this is not something the user gets to see.

**Comment by mstimberg** [comment]
Oh and we should at the same time also introduce the `EventMonitor` (with `SpikeMonitor(...)` == `EvenMonitor(..., event='spike')` -- I think it is convenient to keep the extra unnecessary class here).

**Comment by romainbrette** [comment]
An example is the calcium-based STDP model of Graupner and Brunel.

**Comment by thesamovar** [comment]
I'd be happy to do this, but we probably need to decide the syntax for specifying events in that case (which I guess we have another issue for somewhere).

**Comment by mstimberg** [comment]
I already started working on this, it's really straight forward. I'll open a pull request soon for comments (there's quite a bit of tests and documentation to update/write, though...). I'm not sure, but I assumed we had agreed on the syntax already, providing a dictionary of event names mapping to tuples of condition/statements:
```Python
group = NeuronGroup(N, '...', events={'myevent': ('Ca > Ca_th', 'some_var = some_value')})
```

**Comment by thesamovar** [comment]
OK let's discuss on the PR when you open it. I don't particularly like the tuple (condition, statements) but it should be straightforward to change that if we have another idea.

**Comment by thesamovar** [comment]
OK, we decided to leave threshold and reset as they are, but maybe add general events. Closing this issue.
