### ISSUE TITLE
Cython magic number file not found

### ISSUE THREAD

**Issue by ulyssek** [brian-team/brian2#1081]
Hi there,

And thanks for the incredible work you've done here. I'm having an issue though, trying to run my network.

Sometimes, randomly (as far as I could notice), brian is raising a weird error : 

```
 File "/home/uk259060/neuron_paper/rebuild/first_script.py", line 1, in <module>
    import brian2 as brian
  File "/home/uk259060/.local/lib/python3.5/site-packages/brian2/__init__.py", line 188, in <module>
    _check_caches()
  File "/home/uk259060/.local/lib/python3.5/site-packages/brian2/__init__.py", line 186, in _check_caches
    check_cache(target)
  File "/home/uk259060/.local/lib/python3.5/site-packages/brian2/__init__.py", line 120, in check_cache
    size = _get_size_recursively(cache_dir)
  File "/home/uk259060/.local/lib/python3.5/site-packages/brian2/__init__.py", line 110, in _get_size_recursively
    total_size += os.path.getsize(os.path.join(dirpath, fname))
  File "/usr/lib/python3.5/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/home/uk259060/.cython/brian_extensions/_cython_magic_2e70926cb011b8d95f8bec0c60cfe8e8.cpp'
```

It happens some time on my computer, and very often on the distant computing server I'm using to run my simulation.

Any idea what could be happening ? If you need more info, please tell me.

Thanks again,

**Comment by mstimberg** [comment]
The error occurs in the `check_cache()` function that it calls at the start of each `brian2` import – its purpose is to notify the user when the Cython cache directory (which stores the cached generated source code) takes up a lot of space on disk.

The error message indicates that a file that was present when Brian looked at the directory content was no longer there when Brian tried to check its size. I guess this can happen when you run multiple Brian processes in parallel. One of the processes generates source code and compiles it, and then deletes the source code, only keeping the compiled version. If another process is started during that time it might happen that it sees the source code file but when it tries to determine its size, it is no longer there.

We should make this more robust, this is something I did not think about when we introduced this mechanism.

At the moment, I see two possible workarounds:
1. You set the `codegen.max_cache_dir_size` preference to 0, which switches off `check_cache`
2. You set the `codegen.runtime.cython.delete_source_files` preference to `False`, so that source files are no longer deleted after compilation.

If you go for solution 1, note that you have to set this preference *before* you import `brian2`. This is only possible if you set the preference via a file (see https://brian2.readthedocs.io/en/stable/advanced/preferences.html#preference-files)

**Comment by ulyssek** [comment]
Thanks a lot Marcel, I'll try this
