### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by ulyssek** [brian-team/brian2#1083]
Hi there,

I'm working with a brian spiking network. Everything is going fine when I launch it for small number of neurons (1 500).

But when I'm using more neurons (15 000) I'm having sometimes Segmentation Fault errors.

No idea how to debug that...

Thanks a lot,

**Comment by mstimberg** [comment]
Hi,
this is almost certainly a bug in Brian itself. The best way to debug this kind of issues is to switch to the Python fallback mode by setting
```Python
prefs.codegen.target = 'numpy'
```
at the beginning of your script. Instead of a segmentation fault, you'll probably get some kind of indexing error. To help us looking further into this issue, we'd also need some (as simple as possible!) example that triggers the problem.

**Comment by mstimberg** [comment]
Closing this for now because we cannot do anything without further information. Please feel free to reopen.

**Comment by ulyssek** [comment]
Thanks, I'm working on something else right now, but I'll dig into my issue as soon as I'll find some time.


thanks a again
