### ISSUE TITLE
Event monitor to store network state

### ISSUE THREAD

**Issue by tristanstoeber** [brian-team/brian2#1124]
Hey,

I am trying to store the complete network state (membrane potentials and conductances of all neurons) of a spiking neural network whenever a spike occurs in any of its neurons.

I was hoping this would be possible with the EventMonitor. But it seems only to apply to the neuron eliciting the spike.

Any ideas how to achieve this efficiently?

Obviously, one could use a state monitor throughout the whole simulation and then select only the time bins that correspond to the spikes. However I want to simulate 5000 neurons for 10 minutes and I am afraid this would blow any memory.

Best wishes from Oslo,
Tristan

**Comment by mstimberg** [comment]
Hi Tristan. Indeed, to record events with an `EventMonitor` you need an event on the neuron that you'd like to record. I can see two solutions to your problem:

1. Instead of an `EventMonitor`, you can use a `network_operation` (this only works if you use standard runtime mode). Basically you write a Python function where you check every time step whether `group.spikes` is empty, and if it isn't, you manually save `group.v` and whatever else you are interested to a list that you created outside of the function.

2. You use `Synapses` to trigger an event in all neurons, if one of them spikes. This is compatible with standalone mode and should therefore be faster, but it adds a bit of spike propagation (but if spikes are relatively rare, this should be still faster than the above solution where you run a Python function every time step). This is not that complicated, but you have to be careful with the [scheduling](https://brian2.readthedocs.io/en/stable/user/running.html#scheduling). Here's an example showing how this would work:

```Python
from brian2 import *
tau = 10*ms
group = NeuronGroup(10, '''dv/dt = -v/tau + tau**-0.5*xi : 1
                           record_me : boolean''',
                    threshold='v>1', reset='v=0',
                    events={'record_me': 'record_me'})
group.thresholder['record_me'].when = 'after_synapses'
group.run_on_event('record_me', 'record_me = False')
# Propagate spike information to everyone
propagate = Synapses(group, group, on_pre='record_me = True')
propagate.connect()
group.v = 'rand()'
spike_mon = SpikeMonitor(group)
event_mon = EventMonitor(group, 'record_me', variables=['v'],
                         when='before_resets')
run(50*ms)

plt.scatter(event_mon.t/ms, event_mon.i, c=event_mon.v)
plt.colorbar()
plt.plot(spike_mon.t/ms, spike_mon.i, 'ko', mfc='none')
plt.show()
```
This defines a new `record_me` event, that gets triggered by a variable of the same name. Whenever a neuron spikes, it sets the `record_me` variable of all the other neurons to `True`, then an `EventMonitor` records variables from all neurons where this variable is `True`, and finally we reset the value to `False` (you can use `print(scheduling_summary)` to get a clearer idea about the order of operations). If you run this, you end up with a plot where the membrane potential is colour coded for each neuron whenever one of them (circled in black) spikes:
![Figure_1-2](https://user-images.githubusercontent.com/1381982/67223998-995b0f00-f430-11e9-9e41-1b7bc0b0697c.png)

**Comment by tristanstoeber** [comment]
Hey Marcel!

Thanks for providing this solution! I implemented it and it works as it should! Very much appreciated!

Thinking more about the problem I need to solve I realized two missing points.
When resetting the network state we lose information about undelivered spikes and, more importantly, which neurons are actually refractory.

Do you see some solution to that?

I assume the most elegant solution would be to call network.store() after each spike. Do you see any possibility for that?

Less elegant, yet maybe easier to realize, is to reconstruct from the delays which spikes are not yet delivered and add them with a spike generator. Is it possible to directly control whether a neuron is in a refractory state? If not, one may add a second variable to the neurons' equations that controls only whether a neurons remains refractory or not.

Input very much appreciated.

Best wishes,
Tristan

**Comment by mstimberg** [comment]
I'm afraid I don't quite understand. What do you mean by "resetting the network state"? My example above does not have refractoriness, but I do not see what would change if you added it. I though the whole `EventMonitor` question was about *recording*, why would it interfere with undelivered spikes and refractoriness?

**Comment by tristanstoeber** [comment]
Thanks for your prompt answer. I will try to give a bit more context to make the point clearer.

I am creating simulation data to test a method to make causal inferences about connections by using wide field optogenetic stimulations https://www.biorxiv.org/content/10.1101/463760v2
In short we compare the response of a downstream neuron to the stimulation when a potential presynaptic neuron was in a responsive state or when it was in a refractory state (and therefore unable to respond to the stimulation).

To reduce the simulation load, we want to avoid having to simulate the time between stimulations and we want to target the stimulation to hit when we know that a neuron is refractory.

In practice, I want to achieve the following: I want to first run a simulation where I record the network state at each given spike. Then in a second simulation, I want to restore the network state of any of those spike time points and run it two times with or without optogenetic stimulation.

So ideally I would like to store/restore the full network state at any spike time. Or alternatively store/restore all variables that allow me to restore the network state. In our network these are membrane potential, excitatory and inhibitory conductances, refratory states and some undelivered spikes.

**Comment by tristanstoeber** [comment]
A potential third alternative would be to use network store/restore in its current form but at the right time points.
I expect that there is no way to halt a simulation because of the occurrence of some events, like a spike?
If this is not possible, would using the same numpy seed for poisson input lead to exactly the same spike times in two instantiations of the same network or would it suffer from some numerical rounding issues over time? If the seed is to be trusted, one could store network states by running to simulations. First simulation to just record spike times. Then second, simulate the snippets between the spikes. At the end of each snippet, save network state, run next snippet, save network state and so on ... Do you think this would be an option?

**Comment by mstimberg** [comment]
Ok, I understand your problem a bit better now. If you set the seed, then the simulation should be perfectly reproducible. Note that Brian has its own `seed` function, use this instead of numpy's seed – there's some additional buffering of random numbers behind the scenes. But the problem is that the random number state is not preserved if you do store/restore, so I don't see how you could do a second run that measures the activity after spikes with additional stimulation.

About halting the simulation: you can do these kind of things in network operations (i.e., runtime mode). As I said above, the random number generator state is not preserved when you use store/restore, though, so if you want to have the *exact* same simulation, except for some additional stimulation, you will need to do this manually. This is quite an interesting use case of network operations, actually! There are a few things that are tricky to do correctly: while restore does not preserve the random number generator state, it *will* restore the internal state of monitors. We'll therefore have to store things separately.
But it should be doable, here's an example that shows this approach in a little toy example with a single neuron and an additional stimulation:
```Python
from brian2 import *

seed(1234567)
tau = 10*ms
G = NeuronGroup(1, '''dv/dt = (-v + I_stim)/tau + tau**-0.5*xi : 1
                      I_stim : 1 (constant)''',
                threshold='v>1', reset='v=0')
spike_mon = SpikeMonitor(G)
mon1 = StateMonitor(G, 'v', record=0)
mon2 = StateMonitor(G, 'v', record=0)

@network_operation
def stop_for_spikes():
    if len(G.spikes):
        stop()

# We'll monitor with monitor 1 during the "normal run" and with monitor 2 during
# the run with additional stimulation
mon2_t, mon2_v = [], []
mon2.active = False
runtime = 100*ms
run(runtime)
while defaultclock.t < runtime:
    store()
    # We'll need an explicit seed here, otherwise we'll continue with different
    # random numbers after the restore
    use_seed = randint(iinfo(np.int32).max)
    seed(use_seed)
    # Run with additional stimulation for 10ms
    mon1.active = False
    mon2.active = True
    G.I_stim = 1
    run(10*ms)
    # go back to initial point and continue run (without stimulation)
    # Note that this would reset monitor 2 as well, so we store its data elsewhere
    mon2_t.extend(mon2.t/ms)
    mon2_v.extend(mon2.v[0])
    restore()
    seed(use_seed)
    mon1.active = True
    mon2.active = False
    run(100 * ms - defaultclock.t)

plt.plot(mon1.t/ms, mon1.v[0])
plt.plot(mon2_t, mon2_v)
plt.plot(spike_mon.t/ms, np.ones_like(spike_mon.t), 'rx')
plt.show()
```

This generates a plot like this:
![Figure_1-3](https://user-images.githubusercontent.com/1381982/67772194-ef940780-fa59-11e9-9d7a-a4c60e43a4eb.png)

The blue line is the normal simulation, and the orange lines are a 10ms simulation with additional stimulation after each spike occurrence (ignore the line connecting the two segments). Note that if you record many variables, using [`mon.get_states`](https://brian2.readthedocs.io/en/stable/user/models.html#storing-state-variables) might come handy.

**Comment by mstimberg** [comment]
Hah, good point! Fortunately, this is easy to cope with: after the annotation with `@network_operation`, the `stop_for_spikes` function is a "Brian object" like all the other elements of your simulation, so you can use:
```Python
stop_for_spikes.active = False
```
before and
```Python
stop_for_spikes.active = True
```
after the "stimulation simulation" to disable/enable it appropriately.

**Comment by tristanstoeber** [comment]
Implemented and it generally does the job!
However I realized one problem. I want to condition the stopping and branching out of the regular simulation only on the spikes of the stimulated subgroup.
However it seems that the branching points do also happen when this subgroup is not spiking.
What exactly is the content of .spikes? Are those the id's of all neurons that spiked for the full group?

**Comment by tristanstoeber** [comment]
This is how I try to restrict the network operation to the subgroup

`@network_operation
def stop_for_spikes():
    if len(nodes_ex_stim.spikes):
#    if len(np.in1d(nodes.spikes, nodes_ex_stim_i)):
        stop()`

And this is how the loop looks like

`# run init time without stimulation
stop_for_spikes.active = False
run(p['init_simtime'])
sys.stdout.write('\r'+str(defaultclock.t/ms))

# now with stimulation
stop_for_spikes.active = True
run(p['runtime'] - defaultclock.t)

while defaultclock.t < p['runtime']:
    # stimulation only after init_simtime 
    stop_for_spikes.active = False
    t2 = defaultclock.t/ms
    # store network state before stimulation
    store()
    # We'll need an explicit seed here, otherwise we'll continue with different
    # random numbers after the restore
    use_seed = randint(iinfo(np.int32).max)
    seed(use_seed)
    # change spike monitors
    spk_mon1.active = False
    spk_mon2.active = True
    # stimulate
    nodes_ex_stim.I = p['stim_amp_ex']
    run(p['stim_duration'])
    # turn stimuli off, but keep on simulation
    t_left = p['simtime_stim'] - p['stim_duration']
    nodes_ex_stim.I = 0.*pA
    run(t_left)
    # store data of intermittent run
    spk_mon2_t[t2] = np.array(spk_mon2.t/ms)
    spk_mon2_i[t2] = np.array(spk_mon2.i).astype(int)
    # restore previous network state and continue with simulation
    stop_for_spikes.active = True
    restore()
    seed(use_seed)
    spk_mon1.active = True
    spk_mon2.active = False
    sys.stdout.write('\r'+str(defaultclock.t/ms))
    run(p['runtime'] - defaultclock.t)`

As you can see, I determine the timepoints of the branching out by defaultclock.t

**Comment by mstimberg** [comment]
> What exactly is the content of .spikes? Are those the id's of all neurons that spiked for the full group?

Ah yes, indeed. The `.spikes` attribute is a user-friendly representation of what is used internally (I don't think any Brian code uses the `.spikes` attribute directly), and it is not adapted to subgroups (which don't copy any information, but are only "views" on the actual group). So you'll have to check for the spikes being in the subgroup yourself, e.g. by something like
```Python
    spikes = nodes_ex_stim.spikes
    start, stop = nodes_ex_stim.start, nodes_ex_stim.stop 
    if len(spikes) and any((spikes>=start) & (spikes<stop)):
```
If you have many spikes in the full group at every time step, this might be somewhat slow because you are going through the full list of spike indices every time. The list of indices is sorted, so there is room for more efficient checks. E.g., if the first index is already `>= stop`, or if the last index is `< start`, you do not have to check the rest of the list, or you could use [`np.searchsorted`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.searchsorted.html) to find `start` and `stop` in the list efficiently (in logarithmic time), etc. But I doubt this will make a difference for modest numbers of spikes.

**Comment by tristanstoeber** [comment]
Thanks Marcel.

Just a last small point. The time points of the branching in comparison to the spikes that cause the branching seem to be shifted by 0.2 ms.
With branching I mean when we store, stimulate and restore the network.

I realized this when trying to align the branching points with the spikes of the stimulated neurons.
In the following figure, the network only branched into stimulation, when any neuron with an id between 0 to 100 spiked.
The upper plot shows the unshifted and the lower plot the shifted case.
![Screenshot from 2019-11-04 12-49-15](https://user-images.githubusercontent.com/17001820/68118935-961c5480-ff01-11e9-9d25-782173ce32c4.png)

**Comment by mstimberg** [comment]
Hi,
I think this is because by default, a `network_operation` is executed in the `start` slot of the time step (see the [scheduling documentation](https://brian2.readthedocs.io/en/stable/user/running.html#scheduling)) – it will therefore stop the simulation in the time step following the time step where the spike occurred. I'm not 100% sure why you see a *two* time step difference, but it might be that when you continue the simulation, it actually skips the time step in which it was stopped (if you stop at time step `t`, it will continue at time step `t + dt`). Can you check whether changing the `network_operation` decorator to `@network_operation(when='end')` fixes the issue?

**Comment by tristanstoeber** [comment]
Thanks for your prompt answer again! :+1: '@network_operation(when='end')' leaves a shift of 0.1 ms

**Comment by tristanstoeber** [comment]
Ok I would say, I can live with that! Thanks you very much for all the help! I feel it is time to close the issue. In case we see each other one day, please remind me that the beer is on my bill! :D

**Comment by mstimberg** [comment]
> '@network_operation(when='end')' leaves a shift of 0.1 ms

I had another look and I realized that this is expected. When you call `stop()` in the `network_operation`, we do not stop the simulation right away but only at the end of that time step. The last action of a time step is to prepare the clock for the next time step, so `defaultclock.t` will always be one `dt` bigger than the event that made the simulation stop.

**Comment by tristanstoeber** [comment]
Ok this makes sense. Then I can be sure that hardcoding a shift of 0.1 ms will work in all cases.

**Comment by tristanstoeber** [comment]
Hei Marcel,
when running the simulation for a long time, it seems like the /tmp folder is getting clogged with brian files of several gigabytes in size. Is it possible that store/restore keeps those states? can i free them from memory somehow? i tried to save them by giving them a filename, but there it complains that it can not pickle weakref objects. Any idea?

**Comment by mstimberg** [comment]
Hi, indeed this is a problem for long-running simulations. The files should be deleted after the end of the script (if no error occurred), though. We mention this problem and a solution via a preference file in the documentation, but I have to admit it is not very easy to find.... https://brian2.readthedocs.io/en/stable/advanced/logging.html#preferences
