### ISSUE TITLE
Segmentation fault when monitoring more than 2**31 neuron states

### ISSUE THREAD

**Issue by Debilski** [brian-team/brian2#1136]
The `StateMonitor` example from the brian2 [user’s guide](https://brian2.readthedocs.io/en/stable/user/recording.html) segfaults

```
N=215
G = NeuronGroup(N, '''dv/dt = (1-v)/(10*ms) : 1
                      v_th : 1''',
                threshold='v > v_th',
                # randomly change the threshold after a spike:
                reset='''v=0
                         v_th = clip(v_th + rand()*0.2 - 0.1, 0.1, 0.9)''')
G.v_th = 0.5
M = StateMonitor(G, 'v', record=True)
run(1000*second)
```
when run for 1000 seconds and with `N=215`. `N=214` finishes without problem and we have `M.v.shape == (214, 10000000)`, which is just below the maximum value of an int32, 2,147,483,647.

With `prefs.codegen.target = 'numpy'` it runs without any problem.

**Comment by Debilski** [comment]
Changing the `cdef int`s to `cdef long long` in https://github.com/brian-team/brian2/blob/master/brian2/codegen/runtime/cython_rt/templates/statemonitor.pyx avoids the segfault. But I have no idea what this implies (read: I didn’t check if the results look correct). If this looks like a feasible solution, I am happy to spend more time on it and submit tests and a bug report.

**Comment by Debilski** [comment]
Now that I dug a little deeper into the brian2 codebase: Is there a particular reason that brian2 isn’t using `Py_ssize_t` for array indexes and how complicated would it be to change it? (See https://cython.readthedocs.io/en/latest/src/userguide/numpy_tutorial.html#adding-types and https://www.python.org/dev/peps/pep-0353/)

**Comment by mstimberg** [comment]
Hi, thank you for your report. We have unfortunately hardcoded `int` in quite a few places (there are probably some "TODO" comments in the code about that). It hasn't been that much of an issue so far, since you are typically limited by your memory before you hit the 32 bit limit. For example, in your code you'll need ~16GB of RAM just to record the *v* variable. I guess having significantly more than 16GB available becomes more and more common.

There are a number of issues here (e.g. should we warn the user if a monitor takes up a lot of memory?), but I agree that there is no good reason for data types only used for indexing to be hardcoded to `int`. The question is a bit different for e.g. synaptic indices, but let's ignore that for now.

I think we do not necessarily need `Py_ssize_t`, this is a bit specific to the needs of Python (negative indices, etc.), I think in most cases we could simply use `size_t`. I'll have a look into this, maybe we can still squeeze a fix it into the upcoming release.

**Comment by Debilski** [comment]
Yeah, our users here regularly run with > 100GB of RAM, so I’m almost guessing it is not the first time this has happened here. (But since the code only crashes with a segfault – and only after hours in the simulation –, it is very unclear to most of them how to figure out what went wrong.)

(Not sure I understand the reasoning for `size_t` though. I would have thought that `Py_ssize_t` makes sense for the very reason that it is specific to the needs of Python/numpy.)

In any case we’re happy to help out and test our simulations on any fixes that there may be.

**Comment by mstimberg** [comment]
> (Not sure I understand the reasoning for `size_t` though. I would have thought that `Py_ssize_t` makes sense for the very reason that it is specific to the needs of Python/numpy.)

What I meant is: `Py_ssize_t` was introduced to be the *general* index type in Python that should work in all places where `int` was used previously. In our case, we are discussing to replace the type in situations  like `cdef int new_size = old_size + 1` -- we can safely use an unsigned type (i.e. `size_t`) here, we do not have to use a signed type to deal with negative indices, etc.
