### ISSUE TITLE
Synapses.connect(): Illegal instruction

### ISSUE THREAD

**Issue by nfzd** [brian-team/brian2#1182]
Hi,

my code fails unexpectedly, I distilled the problem down to this:

```
from brian2 import NeuronGroup, Synapses

n = NeuronGroup(2, 'dx/dt = -x : 1', threshold='x > 1', reset='x = 0')

syn = Synapses(n, n, on_pre='x_post += 1')

syn.connect(i=0, j=1)  # fails with "Illegal instruction"
```

This seems weird. Any idea why it fails? How can I debug this? Thanks.

**Comment by nfzd** [comment]
Installing the latest version somehow solved the problem.

**Comment by nfzd** [comment]
Installing the latest version somehow solved the problem.

**Comment by mstimberg** [comment]
Sorry, I overlooked this bug report earlier. Brian itself would never raise "Illegal instruction", so this must have been an issue in the underlying Cython/C++ code. Maybe it was due to some broken compiled file left-over in the cache (which you can clear with `clear_cache('cython')`. As a side-effect of your update, it probably regenerated the file and made the error go away.

Either way, happy that it works for you now. Please reopen the issue if the error reappears.

**Comment by nfzd** [comment]
The error reappeared, it seems to happen every time our servers get updated (which probably includes updates for cython etc.). It ran `clear_cache("cython")` straight away this time, and it fixes the problem. Just mentioning this to confirm that the suggestion by @mstimberg works (thanks!) in case anyone else runs into this issue agan.
