### ISSUE TITLE
Unexpected error from from brian2 import time

### ISSUE THREAD

**Issue by Aman-A** [brian-team/brian2#1185]
Hi, I installed brian2 in a fresh conda environment and got errors when trying to run old code that apparently is caused by any calls to the 'time' function. Just running "from brian2 import time" gives the following error:

ERROR      Brian 2 encountered an unexpected error. If you think this is bug in Brian 2, please report this issue either to the mailing list at <http://groups.google.com/group/brian-development/>, or to the issue tracker at <https://github.com/brian-team/brian2/issues>. Please include this file with debug information in your report: /var/folders/ly/hz006lz92zdgh2zrzr_b_r_h0000gn/T/brian_debug_xnm4621g.log  Thanks! [brian2]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'time' from 'brian2' (/Users/amanaberra/opt/anaconda3/envs/brian2_env/lib/python3.7/site-packages/brian2/__init__.py)

I've attached the error log. Also, not sure if this is related, but running brian2.test() fails several tests, I can attach the output from that if it's helpful.

Thanks!

[brian_debug_xnm4621g.log](https://github.com/brian-team/brian2/files/4602814/brian_debug_xnm4621g.log)

**Comment by mstimberg** [comment]
Hi. There is no package called `time` in Brian, so you shouldn't import it from there. There's a module `time` in the standard library, and I think we make (or made) it accidentally available from the Brian package, since it is used internally. If this is the package you want to use – and I don't really see what else this would refer to – then it should work if you replace `from brian2 import time` by `import time`.

Failing tests (if they are actual failures and not just skipped tests) are a problem, so please share the output from these. However, your log states that you are using an outdated Brian version, so please update it first with `conda update -c conda-forge brian2`.

**Comment by Aman-A** [comment]
I see, I was initially getting an error from previously working code when calling time.time(), thought it was a Brian function. I ended up doing a fresh install in a separate environment with python 3.8 and all the tests pass now, so I think everything is ok. Thank you!
