### ISSUE TITLE
brian_debug file log fills up /tmp folder

### ISSUE THREAD

**Issue by Debilski** [brian-team/brian2#1188]
On longer Brian sessions, I am noticing that Brian’s debug log in `/tmp/brian_debug_….log` gets to a few GB easily, or > 50GB on some occasions, a single user running Brian can quickly eat up either all of `/tmp` or the complete root file system (or easily the whole of memory, in case of a tmpfs), annoying all other users on the computer.

With people running Brian from inside their Jupyter sessions, I assume that the debug files will also be deleted much rarely (as the Jupyter kernel process will just keep running and no cleanup routine is started) as compared to just running Brian from a command line script.

Would it be feasible to implement some continuous cleanup strategy in this case? Even a simple rotating handler might help a little, because then we can at least delete older files manually to free some space. (Deleting the still-opened file won’t help as long as the process is running.)

**Comment by thesamovar** [comment]
Deleting them or rotating is tricky because we don't keep track of the log files and no obviously good way of doing so. I believe at the moment the logs are deleted at the end of a script if there was no exception raised, although not sure how that works with Jupyter. How about just turning off logging if you don't need it?

**Comment by Debilski** [comment]
I agree that turning it off might solve it for me personally, but I guess that the debug log can be quite useful once in a while (otherwise why would the Brian default be to turn them on), especially in a longer Jupyter session with a bunch of back and forth experimenting. If nothing else works, it would still be nice if there were a command to just flush the debug log from inside Brian.

The bigger problem for me though is that I am administering the compute servers for other people and therefore have to expect that there will always be some who have not set the option. (It is a little unfortunate if I then have to tell a user that I had to kill their Brian simulation after a week or so, because we ran out of tmp space.)

Python comes with a [logging.handlers.RotatingFileHandler](https://docs.python.org/3/library/logging.handlers.html#logging.handlers.RotatingFileHandler) where one can set a maximum byte size. Could this not be an option perhaps?

**Comment by thesamovar** [comment]
Oh! I've learned a new thing today. That could indeed be quite helpful. We'd need to experiment with that.

**Comment by Debilski** [comment]
Cool. Thanks for taking a look.

**Comment by thesamovar** [comment]
If you fancy having a go at implementing it and submitting a PR, we might be able to get this into the next release. Sounds like it might not be a lot of work?

**Comment by Debilski** [comment]
Yeah, I can try. I will see if I can get something submitted in the coming week.

**Comment by mstimberg** [comment]
Just to give my 2 cents: I agree with the general observation that our current log handling is a problem. When we designed it, I think we were not really taking into account situations where the Python process stays open for a long time. Nowadays, this has become quite common though. You mentioned jupyter kernels, but the same also holds for execution in some IDEs which either optionally or by default execute things continuously in the same (i)python terminal.

> The bigger problem for me though is that I am administering the compute servers for other people and therefore have to expect that there will always be some who have not set the option.

Do all users use the same Brian installation or do they all have their own? If they all use the same, you could change the default preferences in the `default_preferences` file in Brian's installation directory. Setting the `logging.file_log_level` preference to `DEBUG` instead of `DIAGNOSTIC` (which is *very* verbose) should already make a considerable difference. I thought about changing this default in general, actually.

But this is a bit of a band-aid. As mentioned before, the current system is not adapted to a long running Python process at all. We do delete the script after exit if no exception was raised, but if you run in the same process for a long time, chances are high that an exception was raised at some point and therefore the log file will never get deleted...

I think a good (but not entirely trivial) approach to deal with most of the issues would be to not only close/delete logs at the end of the Python process. Instead, it should close (and reopen a new one) if:
* an exception was raised (to prevent that this exception "keeps alive" future logs)
* `start_scope()` is used (because this means we are clearly starting a new simulation)

There are more complex situations that are in principle comparable to a call of `start_scope` (e.g. the construction of a new `Network`object), but things can quickly get complicated and I'm not sure it is worth the effort. To be honest, the log has never been that useful to me when someone sent it together with a bug report ­– the most useful part has probably been the beginning where it states the versions of all dependencies.

In addition to the above solution it would indeed be a good thing to have a `RotatingFileHandler` with a maximum log size ­– I can't really think of a situation where a 1GB log would be helpful...

**Comment by thesamovar** [comment]
I'd say let's switch to RotatingFileHandler by default, and then we don't need to worry about the ``start_scope()`` rule. I'm also happy to downgrade to debug instead of diagnostic since it's rarely if ever useful in practice.

**Comment by Debilski** [comment]
> Do all users use the same Brian installation or do they all have their own? If they all use the same, you could change the default preferences in the default_preferences file in Brian's installation directory. Setting the logging.file_log_level preference to DEBUG instead of DIAGNOSTIC (which is very verbose) should already make a considerable difference. I thought about changing this default in general, actually.

Everyone has their own Brian installation, unfortunately. Curiously, in recent weeks I have observed the problem much more often than earlier. I wonder if the usage patterns of our servers maybe changed due to home office etc.

I have added a fix that uses the `RotatingFileHandler` in https://github.com/brian-team/brian2/pull/1193 
As I am not a regular Brian user myself, I am not sure I can help with the non-trivial approach to fixing this problem.

**Comment by mstimberg** [comment]
Closed via #1193
