### ISSUE TITLE
Does brian2 or brian2genn support 'for' loops?

### ISSUE THREAD

**Issue by jcmharry** [brian-team/brian2#1201]
Hi, I'm trying to run the MNIST classifier code [https://github.com/henokhope1/stdp-mnist-brian2/blob/master/spiking.py](url), but it's really very slow. It takes several days to train the SNN. So I want to know cpp_standalone or brian2genn support 'for' loops? Or any other ideas to speed up the training process? Thanks.

**Comment by mstimberg** [comment]
[In the future, please direct questions or error reports where you are not sure whether it is "Brian's fault" to Brian's [support mailing list](https://groups.google.com/forum/#!forum/briansupport) (briansupport@googlegroups.com), we try to keep the github issues for bugs and feature requests.]

It depends on what you mean by "for loops". Yes, cpp_standalone does support having more than one `run` statement, but there are some [limitations](https://brian2.readthedocs.io/en/stable/user/computation.html#limitations). Brian2GeNN only supports a single `run` statement. Regardless of what mode you are using, you should try to minimize the number of `run` statements, though. Have a look at the [documentation](https://brian2.readthedocs.io/en/stable/user/input.html) on how you can make inputs change during a run. A simple example: Instead of using this:
```Python
poisson_group = PoissonGroup(100, rates=50*Hz)
for _ in range(5):
    poisson_group.rates = np.random.rand(100)*50*Hz
    run(200*ms)
```
you can use:
```Python
poisson_group = PoissonGroup(100, rates=50*Hz)
poisson_group.run_regularly('rates = rand()*50*Hz', dt=200*ms)
run(1000*ms)
```

**Comment by jcmharry** [comment]
Thanks for your reply. But if I want to train my SNN model using loops rather than emitting spikes, how can I speed up my loops？
An example is like this:

while j < 1000:
    if test_mode:
        rate = testing['x'][j%10000,:,:].reshape((n_input)) / 8. *  input_intensity
    else:
        normalize_weights()
        rate = training['x'][j%60000,:,:].reshape((n_input)) / 8. *  input_intensity
    input_groups['Xe'].rates = rate * Hz
    net.run(single_example_time, report='text')
    current_spike_count = np.asarray(spike_counters['Ae'].count[:]) - previous_spike_count
    previous_spike_count = np.copy(spike_counters['Ae'].count[:])
    if np.sum(current_spike_count) < 5:
        input_intensity += 1
        input_groups['Xe'].rates = 0 * Hz
        net.run(resting_time)
    else:
        if test_mode:
            result_monitor[j,:] = current_spike_count
            input_numbers[j] = testing['y'][j%10000][0]
        if j % 100 == 0 and j > 0:
            print 'runs done:', j, 'of', int(num_examples)
        input_groups['Xe'].rates = 0 * Hz
        net.run(resting_time)
        input_intensity = start_input_intensity
        j += 1
