### ISSUE TITLE
Additional numpy functions that don't work as expected

### ISSUE THREAD

**Issue by kjohnsen** [brian-team/brian2#1212]
Just ran into a couple of numpy functions that stripped quantities off arrays, which weren't in the [documentation](https://brian2.readthedocs.io/en/stable/developer/units.html#numpy-functions)
* `matmul` and accompanying `@` operator
  * Example: `np.eye(2) @ np.array([[2],[3]]*mm)`
  * Output: `array([[0.002], [0.003]])`  (no quantity)
* `np.linalg.norm`
  * Example: `np.linalg.norm(np.array([1, 0]*mm))`
  * Output: `0.001` (again, no quantity)

**Comment by mstimberg** [comment]
Sorry for the late reply and thanks for the info! I'll check whether we can make them behave (or otherwise add them to the docs). Note that in your examples you are stripping off the units before passing them to `@` or `linalg.norm` – but you get the same effect if you pass the `Quantity`, so it is a real issue.
