### ISSUE TITLE
Segmentation fault when using N_incoming or N_outgoing in Synapses.connect() condition

### ISSUE THREAD

**Issue by denisalevi** [brian-team/brian2#1227]
```python
from brian2 import *

set_device('cpp_standalone'(

G = NeuronGroup(10, 'dv/dt = 1/(10*ms) : 1', threshold='v>1', reset='v = 0',
                        method='euler')

S = Synapses(G, G, on_pre='v += 1')

S.connect('i < N_incoming')

run(1*ms, profile=True)
```

This fails with a segmentation fault (only tested on Brian 2.3). I think the problem is that in the `synapses_create_generator` template, first the raw pointer from the `N_incoming` vector is extracted, then the vector is resized (and therefore, the memory reallocated) and then the previously extracted pointer is used in `vector_code`. Here the corresponding lines from the generated code:
```cpp
///// CONSTANTS ///////////
int32_t* const _array_synapses_N_incoming = _dynamic_array_synapses_N_incoming.empty()? 0 : &_dynamic_array_synapses_N_incoming[0];

///// pointer lines ///////////
int32_t* __restrict  _ptr_array_synapses_N_incoming = _array_synapses_N_incoming;

_dynamic_array_synapses_N_incoming.resize(_N_post + 0);

//// segmentation fault
const int32_t N_incoming = _ptr_array_synapses_N_incoming[_raw_post_idx];
```

I have the same problem in the CUDA Standalone template. For synapses between neurongroups, one could just move the resizing [here](https://github.com/brian-team/brian2/blob/fcf12bfaf501b83b5e05488e7a5cd9fe96fe6638/brian2/devices/cpp_standalone/templates/synapses_create_generator.cpp#L15-L18) above the `CONSTANTS` and `pointer_lines`. But I guess that would be a problem for synapses between synapses, where `N` is not known before runtime and is declared in `CONSTANTS`? (didn't try it).

**Comment by denisalevi** [comment]
Was just thinking if this should be allowed at all? Since `N_incoming` and `N_outgoing` would be changing during synapse generation. But I guess something like `S.connect(N_incoming < x)` would ensure that there are only at most `x` synapses per presynaptic neuron?

**Comment by mstimberg** [comment]
Nice catch (again ;) )! I tend towards not allowing it. The reason is that the semantics of a `connect` call with a condition is that after that call, the condition holds true for all synapses that were generated. If the condition itself depends on the number of synapses, this does not work obviously. Also, we allow to create more than one synapse with the `n` parameter, and between the creation of these synapses we do not check the condition any more. Finally, results would depend on the order in which synapses are generated, and I don't think we want that in general.
Finally, `N_incoming` and `N_outgoing` are not updated at all until the end of the `connect` operation in the numpy implementation, so it would work differently there.
Ok, I now convinced myself that we *really* should not allow it :)

In most cases I think it is a better solution to limit the number of synapses with a special syntax (a feature we've discussed for a *long* time: brian-team/brian2#664).

**Comment by denisalevi** [comment]
Ah yes, this sounds convincing!

Also #644. Not that I used that myself by I know that at least two people in my lab spent some thought in the past on trying to fix in- and out-degree with random connectivity.
 
> Nice catch (again ;) )! 

Yeah, I keep testing the `connect` call with all kind of weird stuff because this is the only template in CUDA Standalone that does not have a kernel (using the C++ Standalone implementation). And that tends to need extra care to make things work. Its a bit of a pain but at least it lets some bugs turn up 😂
