### ISSUE TITLE
Error encountered with object named...

### ISSUE THREAD

**Issue by akatav** [brian-team/brian2#1231]
I was trying to step through the code for simulate_LIF_neuron() in jupyter notebook within a cell like below:
```

import brain2 as brian2
V_REST = -70 * b2.mV
V_RESET = -65 * b2.mV
FIRING_THRESHOLD = -50 * b2.mV
MEMBRANE_RESISTANCE = 10. * b2.Mohm
MEMBRANE_TIME_SCALE = 8. * b2.ms
ABSOLUTE_REFRACTORY_PERIOD = 2.0 * b2.ms

eqs = """ dv/dt = ( -(v-v_rest) + membrane_resistance * step_current(t,i) ) / membrane_time_scale : volt (unless refractory)"""

neuron = brian2.NeuronGroup(
    1, model=eqs, reset="v=v_reset", threshold="v>firing_threshold",
    refractory=ABSOLUTE_REFRACTORY_PERIOD, method="linear")
neuron.v =   # set initial value

state_monitor = brian2.StateMonitor(neuron, ["v"], record=True)
spike_monitor = brian2.SpikeMonitor(neuron)
%debug brian2.run(300 * brian2.ms)
```

The code errors out in the last line 
`brian2.run(5*brian2.ms)`
 with the following error:
BrianObjectException: Error encountered with object named "neurongroup_6".
Object was created here (most recent call only, full details in debug log):
  File "<ipython-input-81-f233b4d198b2>", line 7, in <module>
    refractory=ABSOLUTE_REFRACTORY_PERIOD, method="linear")

However running the code directly using LIF as below, does not throw an error:
LIF.simulate_LIF_neuron(input_current=step_current, simulation_time=300 * brian2.ms)

**Comment by mstimberg** [comment]
Hi. Could you post a runnable example and the full error message? The `BrianObjectException` only tells you what object (in your case the `NeuronGroup`) raised the error, the actual problem is in the message above it. The code is also a bit hard to read because apparently it mixes the use of `brian2` (i.e. after `import brian2`) and `br2` (`import brian2 as br2`). Not sure how the `import brain2...` line in the beginning is not failing, there is no package named `brain2`. If I correct for these little things, it fails because it does not know what the `step_current` function refers to, maybe this is your issue as well?
You are mentioning `simulate_LIF_neuron` in the beginning, where is this function coming from? Is this from the Neuronal Dynamics book?
From what I can see so far this does not look like an issue in Brian. In general please rather use https://brian.discourse.group for these kinds of questions.

**Comment by mstimberg** [comment]
Do you still have this issue @akatav ? Otherwise I will close the issue.
