### ISSUE TITLE
Error! C:\Users\USER\Desktop\FAITH\output\results\_dynamic_array_spikemonitor_2_t_-5040102116673421125 is not UTF-8 encoded Saving disabled. 

### ISSUE THREAD

**Issue by ramapati166** [brian-team/brian2#1245]
During simulation of Spiking Neural Network using Brian2 at cpp standalone mode "set_device('cpp_standalone', directory='STDP_standalone')
device.reinit()
device.activate()"
after the simulation in the generated output folder in the result section given the list of dynamic file of SpikeMonitor such as 
"_dynamic_array_spikemonitor_2_t_-5040102116673421125".But when I am trying to open the file it showing the above described error.As an alternative if I want to access the spike information such as spike time(t) and corresponding neuron( i) by using SpikeMonitor command it is not showing the complete information.Say I have considered 3 layered neural netwok(first layer for poisson input,hidden layer 28 neurons and output layer 12 neurons) so when I am trying to accessing the spike time information using SpikeMonitor command at the cosole I am getting the result like 
<spikemonitor_2.i: array([ 0,  1,  2, ..., 25, 26, 27])>
<spikemonitor_2.t: array([  3.2,   3.2,   3.2, ..., 499.9, 499.9, 499.9]) * msecond>
How to get the intermediate values which are denoted by "dot"?If anyone can help regarding this issues I will be highly obliged to you.Thanksin advance.

**Comment by mstimberg** [comment]
[In the future, please direct questions or error reports where you are not sure whether it is "Brian's fault" to Brian's [discussion forum](https://brian.discourse.group), we try to keep the github issues for bugs and feature requests.]

The files in the outputs/results folder are binary files used internally by Brian to exchange the values between the C++ simulation and the Python script. They are not supposed to be opened directly, and in particular not with a text editor which I think is what you were trying to do.

The `SpikeMonitor`'s `i` and `t` attribute contain all the values. You can plot them or analyze them in any way you want with the same techniques you'd use for any `numpy` array. Since there are more than 1000 values, not all values get printed on the console by default. If you really want to print all the values, you can [use numpy's `set_printoptions` function](https://stackoverflow.com/questions/1987694/how-to-print-the-full-numpy-array-without-truncation).

**Comment by ramapati166** [comment]
Thank you very much for your reply.I am very sorry sir,from next time I will send the issues to Brian's discussion forum.

**Comment by mstimberg** [comment]
You're welcome and no worries. Make sure to also have a look at the [tutorials](https://brian2.readthedocs.io/en/stable/resources/tutorials/index.html), [examples](https://brian2.readthedocs.io/en/stable/examples/index.html), and the general [documentation](https://brian2.readthedocs.io).

**Comment by ramapati166** [comment]
Definitely sir. Thank you.
