### ISSUE TITLE
Error in unit check?

### ISSUE THREAD

**Issue by sivanni** [brian-team/brian2#1246]
Dear Brian2 development team. I am getting this: "brian2.units.fundamentalunits.DimensionMismatchError: Argument number 1 for function exp does not have the correct units. Expression "(- ((10.0 * meter) / mm)) * sqrt(((x_pre - x_post) ** 2) + ((y_pre - y_post) ** 2))" has units (m), but should be (1). However, when I check the unit manually, there is no mismatch. Also when I back to brian2==2.3, the error goes away.

This issue is similar what was closed in September #1234
Cordially, Simo

**Comment by mstimberg** [comment]
Hi. It seems to run into the expression `exp((- ((10.0 * meter) / mm)) * sqrt(((x_pre - x_post) ** 2) + ((y_pre - y_post) ** 2)))` and this looks indeed wrong (assuming that x and y have units of meter). I think the issue is rather that the units were not correctly checked in `Synapses.connect` statements until recently (see #1224), so Brian 2.3 will let the incorrect expression pass.

**Comment by sivanni** [comment]
Thanks for prompt response. I will check my side.
