### ISSUE TITLE
Possible Bug On Spike Count

### ISSUE THREAD

**Issue by Adam-Antios** [brian-team/brian2#1253]
While using certain spike trains produced by LIF neurons I realized that sometimes Brian would include in the spike count the initial state of the neuron (membrane potential of 0 volts). You can see this behaviour on the following code after running it a few times. I executed my simulations on Linux.

To be more  specific, in some simulations Brian adds one more spike to the spike train of one or more neurons, so for example if I count via the method I built in the code 500 spikes, Brian with the build-in method may count 501. This does not happen in every simulation and it doesn't happen to all neurons.  In order to make sure I had the neurons' voltages saved in files and searched how many 0 volt occurrences existed, excluding the initial state of the membrane potential. 

A curious thing I noticed is that this behaviour is exhibited when the input current remains constant over time (in my simulations I also include a random bias in every neuron as you can see below) and not when it is sinusoidal. I have no clue what this can possibly mean though.

I want to note though that I am not a neuroscientist so it may very well be a better explanation for this than being a bug, which seems a bit far-fetched.

```
from brian2 import *

start_scope()

# =================================
# =================================
# Define the model

# The number of neurons.
n = 5

# Assuming resting membrane potential 0.
# The parameter b is the bias.

neuron_equation_on = '''
    dv/dt = (R*I-v)/tau : volt
    I = 1.5*amp+b : amp
    b : amp
    R : ohm
    tau : second
    '''

group_of_neurons= NeuronGroup(
    N = n,
    model = neuron_equation_on,
    threshold = 'v>1*volt',
    reset = 'v=0*volt',
    method = 'euler')

group_of_neurons.R = [1 for i in range(n)]*ohm
group_of_neurons.tau = [2 for i in range(n)]*msecond
group_of_neurons.b = [random() for i in range(n)]*amp

# =================================
# =================================
# Simulation

neuron_voltage = StateMonitor(
    group_of_neurons,
    variables='v',
    record=True)

neuron_current = StateMonitor(
    group_of_neurons,
    variables='I',
    record=True)

neuron_spikes= SpikeMonitor(group_of_neurons)

run(1*second, report = 'text')

# =================================
# =================================
# Create spike trains

# Iterate over every neuron.
for k in range(n):

    neuron_spike_train= [0 for i in range(len(neuron_voltage.v[k]))]

    # Spike train for the ON neuron

    # The counter starts from 1 so to avoid the first 0 being falsely recognized as a spike.
    for i in range(1, len(neuron_voltage.v[k])):
        if neuron_voltage.v[k][i]/volt == 0.0:
            neuron_spike_train[i-1] = 1
        else:
            neuron_spike_train[i-1] = 0

    # Check the validity of the created spike trains.

    print("---------------------------")
    print("Neuron pair number", k)
    print("---------------------------")
    print("Provided spikes of neurons:", neuron_spikes.count[k])
    print("Calculated spikes of neurons:", sum(neuron_spike_train))
```

**Comment by mstimberg** [comment]
Hi. This does not look like a bug to me, it is rather that your method is sometimes missing a spike. In your method, you do not check for spikes but for the reset of the membrane potential. With the default ['scheduling'](https://brian2.readthedocs.io/en/stable/user/running.html#scheduling), the `StateMonitor` will record the membrane potential at the *beginning* of the time step, and therefore will detect all spikes one time step *after* they occur. If you look at the recorded spike times (either by checking `neuron_spikes.t`, or `neuron_spikes.spike_trains()`) you will see that the "additional spikes" are not at the beginning of the simulation, but rather in the very last time step. I.e., if a spike occurs at 0.9999s, Brian's `SpikeMonitor` will record it but your method will miss it. If you want to make your method count all the spikes, one simple fix is to use `when='after_resets'` in the `StateMonitor` so that it records the values later during the time step. I discussed this issue in a blog post/screen cast recently: https://briansimulator.org/posts/2020/video-scheduling-1/
Having said that, if all you want to do is to have a binary spike train representation, you can use the `SpikeMonitor` information directly without recording the membrane potential. E.g. the following code will create a 2D matrix with the spike train for each neuron in its rows (I'm using Brian's `timestep` function here to avoid numerical issues in converting times to timesteps, but you could also use something like `int(round(..)))`):
```Python
from brian2.core.functions import timestep
binary_spike_train = np.zeros((n, timestep(1*second, defaultclock.dt)),
                              dtype=int)
# Set time steps with spikes to 1
binary_spike_train[s_mon.i, timestep(s_mon.t, defaultclock.dt)] = 1
```

As a minor side remark: if you want to use an abstract neuron model with threshold 1 and resting value 0, then I would not use units because quantities like `1V` look quite odd in the context of neurons. You can remove the units from all variables (i.e. use `... : 1` in the equations), except for the time constant `tau` which has to stay in seconds.

**Comment by Adam-Antios** [comment]
Thank you very much for the detailed answer. The solution you proposed works nicely. One thing I don't understand though is how could the method not work for detected the reset of the neuron? Given that every time a spike is fired the neuron will reset, counting those zero values isn't an exact spike count? As I mentioned, I saved in files the values of the membrane potential and the zero values were precisely what I was counting as a spike count but not always what Brian was counting.

**Comment by mstimberg** [comment]
> One thing I don't understand though is how could the method not work for detecting the reset of the neuron? Given that every time a spike is fired the neuron will reset, counting those zero values isn't an exact spike count?

Please have a look at the links I gave to understand this better. The `StateMonitor` is recording the values at the *beginning* of the time step, so you are only seeing the reset in the *following* time step. This does not make a difference for the overall count (it just shifts all spike times by one time step), *except* if a spike occurs in the very last time step of the recording.

>  As I mentioned, I saved in files the values of the membrane potential and the zero values were precisely what I was counting as a spike count but not always what Brian was counting.

Yes, your method is consistent with the membrane potentials at the beginning of each time step. Brian on the other hand will also count a spike if it occurs in the very last time step of the simulation.

**Comment by Adam-Antios** [comment]
Thank you, now it makes perfect sense!
