### ISSUE TITLE
Interface Brian with Robotics Simulator (pyBullet)

### ISSUE THREAD

**Issue by peschn** [brian-team/brian2#1269]
Hi,

I am developing a SNN for a robotics application. Therefore I want to interface Brian2 with a robotics simulator (pyBullet). The idea is that I generate spikes in Brian2 which are translated into control commands that are executed in pyBullet (so the robotics simulation is evolved one more step). In return I want to feed the sensory information from pyBullet into my SNN (Brian2). 

Question: Is it possible to halt the simulation in Brian after a spike, execute some code (pyBullet simulation) and feed the return values back into Brian?

Thanks a lot for your help.

**Comment by mstimberg** [comment]
Hi. This sounds like a great project! I think the discourse forum (https://brian.discourse.group/) would be a better fit for this discussion, though. We try to keep github to concrete bugs/requests that we need to address in Brian.

Either way, here are a few pointers how you could implement this. I think you have two general options:
The first would be to use a [`network_operation`](https://brian2.readthedocs.io/en/stable/user/input.html#arbitrary-python-code-network-operations), i.e. a Python function that is executed every time step. In that function you could check the `spikes` attribute of your `NeuronGroup`, which contains a list of the indices of the neurons that spikes during that time step (use `@network_operation(when='after_thresholds')` to make sure that it gets triggered at the right moment). You can then pass this information to `pyBullet` and feed back the returned values to Brian.
The second option is to use a [user-defined function](https://brian2.readthedocs.io/en/stable/advanced/functions.html#user-provided-functions) in the `reset`, i.e. a function that gets triggered with every spike. If you have a single value that comes back from `pyBullet`, then you could use this as the return value, i.e. something like `reset='sensor_value = robot(i, t)'` (the `i` argument passes the index of the neuron that spiked and `t` the current time. If you have more than one value, then you could set the values directly in your function with the usual assignment syntax (`group.attribute[indices] = some_new_value`). You'd still need to assign the result to a variable in the `reset` statement, but you could simply always return 0 and write something like `dummy = robot(i, t)`. Now you need to write the `robot` function. The simplest case is where everything is in Python, but by default Brian takes your model description and generates Cython code from it that then gets compiled. In that mode, you'd have to write your `robot` function in Cython as well. To avoid this, you have two options: either you switch everything to Python globablly with `prefs.codegen.target = 'numpy'`, or you only switch the code generation target for the single `NeuronGroup` that needs to communicate with `pyBullet` (which means that other `NeuronGroup`s and `Synapses` can still use the Cython code generation). You'd do this with the admittedly cryptic `group = NeuronGroup(..., codeobject_class=NumpyCodeObject)`. Your function would look something like this:
```Python
@check_units(i=1, t=second, result=1)
def robot(i, t):
    if len(i):  #did any neuron spike?
        #pass over information to PyBullet
    return info_from_pybullet
```

Hope that gets you going! I am going to close the issue here, if you want to discuss this further or have other general questions, please head over to the discourse forum.

**Comment by peschn** [comment]
Great, thanks a lot!!!!
