### ISSUE TITLE
Dynamic delay - how to change dynamically synaptic delays during runtime ?

### ISSUE THREAD

**Issue by adididi** [brian-team/brian2#1297]
Hello !

Is it possible to dynamically change synaptic delays, locally at each synapse, during runtime ?
I wanted to set **adaptation rules for the delays in the synaptic code** but it is written in the doc. that Brian "**no longer allow access to the delay variable in synaptic code**".
So are there any solution to implement dynamic delays with Brian2 ?

**Comment by mstimberg** [comment]
Hi. You cannot change synaptic delays during a run at the moment, see #355 and this recent [thread on the discussion forum](https://brian.discourse.group/t/delays-as-variables/365). You *can* change delays between runs, though.

**Comment by adididi** [comment]
Ok thank you, I guess I have to use Brian v1 then.

**Comment by adididi** [comment]
Do you have any recommendation on the version of Brian that I should use to get this dynamic delay feature ?
I really need it for a project.

**Comment by mstimberg** [comment]
I wouldn't recommend using Brian 1, it has not been developed/supported  for several years now and only works with Python 2. Your best approach would probably to reformulate your learning rule in a way that it does not change the delay during the run but in between runs – I'd imagine a typical learning rule in this context to work on a rather long timescale, so this shouldn't be an issue. I briefly mentioned this in the above linked forum post: instead of changing the delay variable, "store" the changes that you want to do in a variable `delta_delay` for example. Then, stop your simulation every 100ms, 1000ms, or whatever you see fit and apply the `delta_delay` to the actual delay, then continue the simulation.
For further questions, let's continue the discussion on the discussion forum.
