### ISSUE TITLE
plasticity off not working

### ISSUE THREAD

**Issue by WillianSG** [brian-team/brian2#1318]
I'm trying to switch off the plasticity in the synapses for the test phase of my network using the example provided [here](https://brian2.readthedocs.io/en/stable/user/running.html#continuing-repeating-simulations) but it does not work. Here's the code:

```python
import setuptools
from brian2 import *

import matplotlib.pyplot as plt

start_scope()

taupre = taupost = 20*ms
wmax = 0.01
Apre = 0.01
Apost = -Apre*taupre/taupost*1.05

G = NeuronGroup(2, 'v:1', threshold='t>(1+i)*10*ms', refractory=100*ms)

S = Synapses(G, G,
             '''
             w : 1
             plastic : boolean (shared)
             dapre/dt = -apre/taupre : 1 (clock-driven)
             dapost/dt = -apost/taupost : 1 (clock-driven)
             ''',
             on_pre='''
             v_post += w
             apre += Apre
             w = clip(w+apost, 0, wmax)
             ''',
             on_post='''
             apost += Apost
             w = clip(w+apre, 0, wmax)
             ''', method='linear')

S.connect(i=0, j=1)

M = StateMonitor(S, ['w', 'apre', 'apost'], record=True)

S.plastic = False

run(30*ms)

figure(figsize=(4, 8))
subplot(211)
plot(M.t/ms, M.apre[0], label='apre')
plot(M.t/ms, M.apost[0], label='apost')
legend()
subplot(212)
plot(M.t/ms, M.w[0], label='w')
legend(loc='best')
xlabel('Time (ms)')
plt.show()
```
Why the line **S.plastic = False** is not turning plasticity off?

Thx in advance.

**Comment by mstimberg** [comment]
Hi @WillianSG. Since you closed the issue, I guess you figured out things yourself (for everyone else coming across this issue: the variable `plastic` needs to be used somewhere in the equations, e.g. in `on_pre` the statement for `w` could be replaced by `w = clip(w + int(plastic)*apost, 0, wmax)`, and the equivalent for `on_post`). Just as a general comment: this kind of question would be more appropriate for the support forum at https://brian.discourse.group – it is hard to keep the overview over all the open issues here, and we therefore try to restrict them to clear bugs or feature requests. Thanks!
