### ISSUE TITLE
Default network scheduling leads to unexpected spike loss in typical simulation scenario

### ISSUE THREAD

**Issue by denisalevi** [brian-team/brian2#1332]
I was writing up a network that connects a `SpikeGeneratoGroup`, which spikes at every time step, to a single neuron `NeuronGroup`, which should spike for each incoming spike. But due to the scheduling of codeobjects, the neuron spikes only every second time step, which I found rather surprising. Here is an example network:

```python
from brian2 import *

# 1 presynaptic neuron spiking the first 3 time steps
indices = [0, 0, 0]
times = array([0, 1, 2]) * defaultclock.dt
inp = SpikeGeneratorGroup(1, indices, times)

# 1 postsynaptic neuron spiking for each incoming spike
G = NeuronGroup(1, 'v:1', threshold='v>1', reset='v=0')
S = Synapses(inp, G, on_pre='v+=1.1')
S.connect()

mon = SpikeMonitor(G)

run(4 * defaultclock.dt)

print("Spike times:", mon.t[:])
```
This prints:
```
Spike times: [100. 300.] us
```

Given how codeobjects are scheduled, the result makes sense since all `thresholders` are run before all `synapses`, before all `resets`, which results in the following:
1. time step: `SpikeGenerator` spike is emitted, pushed and it's effect is applied to the postsynaptic `NeuronGroup`. But since the `NeuronGroup` `thresholder` is run before the `synpses` (the effect application of the input spike), the `NeuronGroup` will not spike this time step.
2. time step the `thresholder` of the `NeuronGroup` will register the spike from the first time step and after that (in the `synapses` block) the `SpikeGenerator` will push another spike. That spike will have a `v += 1.1` effect on the `NeuronGroup`, but the `NeuronGroup` `resetter` will run after the effect application, hence that voltage increase will be resetted before the next `thresholder` runs and will not be translated into a spike, which is why there is no spike in the second time step.

This means for such a network, the `NeuronGroup` neuron spikes only every second time step. This can be fixed by setting 
```
prefs.core.network.default_schedule = ['start', 'groups', 'thresholds', 'resets', 'synapses', 'end']
```
where I just moved the `resets` before the `synapses` (default is `[..., 'thresholds', 'synapses', 'resets', ...]`).

I would consider this example a typical model use case and was rather surprised to loose those spikes. Just wanted to bring this up in case it wasn't already obvious. If there are other reasons for the current default schedule and if you have already discussed this before, please feel free to just close this issue again. :)

**Comment by mstimberg** [comment]
This can indeed lead to confusion! I actually recorded a little screencast about this topic, and also uploaded it as a blog post: https://briansimulator.org/posts/2020/video-scheduling-2/ Back then, I actually proposed a different change to the schedule, but also used `when='before_synapses'` in the `SpikeGeneratorGroup` so that it triggers the spikes within the same time step when they were generated.
I think there are some good reasons for Brian's default schedule (e.g. there are some synaptic models that are interested in the value of the pre-synaptic membrane potential before it gets reset), but AFAICR the main reason for choosing it was that it was Brian 1's default schedule. But Brian 1 actually also had a concisely named method `update_schedule_groups_resets_connections()` to do the schedule change you did :laughing: 

I have certainly seen models like yours before, but the most important thing to document would probably be to not use such models in the first place :wink: : If you want a group that spikes at specific times, use the `SpikeGeneratorGroup` directly instead of connecting it to another group. If you want a group that spikes every time step, you can use `SpikeGeneratorGroup(1, [0], [0]*ms, period=defaultclock.dt)` or even simpler: `NeuronGroup(1, '', threshold='True')`.

**Comment by denisalevi** [comment]
Alright. I'm using it to test spike propagation, where this kind of network does nicely do the job :). I just wanted to bring it up. If you are happy with the default, I'll close the issue. I have no real preference here, I was just surprised. Having a spike recorded a time step later (as in your screencast) would have been a no-brainer for me. But loosing every second spike entirely was not.

**Comment by mstimberg** [comment]
I completely agree that this is not obvious in your example, but we can't change the default schedule since that would change the results of existing simulations. I think this could be one of the issues covered in some kind of debug mode that we'd been discussing. A variable that goes over the threshold but never gets compared to the threshold would then trigger some kind of warning.
