### ISSUE TITLE
Question: (with Brian2) Can I assign ion properties?

### ISSUE THREAD

**Issue by lungsi** [brian-team/brian2#1344]
Can I set ionic properties, say, internal and external concentration for Na ion and also its reversal potential? Do you have an example?

**Comment by mstimberg** [comment]
Hi. Since Brian models are described by equations, you also decide which properties your model has, and this can include ion concentrations and reversal potentials. In the documentation, we have one example that describes a Calcium current as a non-linear function of intra-/extracellular concentrations and voltage: https://brian2.readthedocs.io/en/stable/examples/frompapers.Destexhe_et_al_1998.html

[In the future, please direct questions or error reports where you are not sure whether it is "Brian's fault" to Brian's [discussion forum](https://brian.discourse.group), we try to keep the github issues for bugs and feature requests.]
