### ISSUE TITLE
Discrepancy in variance for Wiener process with different mean

### ISSUE THREAD

**Issue by albertalbesa** [brian-team/brian2#1371]
Hello team,

We have been trying to understand some results in a stochastic LIF model and, in order to isolate the issue, we bumped into the following:

We have an SDE:

dx/dt = a/tau + sigma/sqrt(tau)*xi

the integration (from t=0 to t=T) of which corresponds (to our understanding) to a Wiener process distributed as 
N(a*T/tau, sqrt(T/tau)*sigma).

We run this simulation for several trials and different values of "a", and observe that the variance of the resulting Wiener process increases with "a". For "a" = 0, we recover the aforementioned variance (sqrt(T/tau)*sigma).

We find this confusing, since "a" (the mean) should not affect the variance of the process. 

Here we include a code snippet to repoduce behaviour. It outputs the the std of the Wiener process plotted as a function of mean "a".

```
def w_process_sim(num_samples, a):
  brian_integrated_x = []
  #clear brian scope to reset any past variables
  start_scope()
  #total size of the network
  N = 1
  #time constant
  tau = 1*ms
  #period
  T = 1000*ms
  #W_process sigma
  sigma = 0.1
  #model
  eqs = '''
  dx/dt = a/tau + sigma/sqrt(tau)*xi : 1
  tau : second
  '''
  #network
  w_process = NeuronGroup(N, eqs, method = 'euler')
  w_process.x = x0
  w_process.tau = tau

  #this stores integrated x after each period T
  @network_operation(dt=T)
  def update_active():
      brian_integrated_x.append(np.array(w_process.x))
  #this resets x to 0
  w_process.run_regularly('''x = 0''', dt=T)

  #run  simulation
  total_time = num_samples*T
  run(total_time, report = 'text')
  #compute std of w distribution
  w_std = np.std(brian_integrated_x)
  return w_std


defaultclock.dt = 0.5*ms
num_samples = 1000
a_values = np.linspace(0, 0.1, 5)
w_std_list = []
np.random.seed(0)
for a in a_values:
  std = w_process_sim(num_samples, a)
  w_std_list.append(std)

#plot std in w as a function of mean (a)
plt.plot(a_values, w_std_list)
```

We also include the code with what we understand is the backend implementation of the Euler integration of the equation, for which we get a value of W process std independent of "a" (and approximately sqrt(T/tau)*sigma).

```
def w_process_numpy(num_samples, a):
  def dx(a, sigma, tau, dt):
    dx = a/tau*dt + sigma/sqrt(tau)*np.random.normal(0, 1)*np.sqrt(dt)
    return dx

  x0 = 0 # unit
  T = 1000 #ms
  dt = 0.1 #ms
  a = 1 #unit
  tau = 1 #ms
  sigma = 0.1 #unit
  timesteps = int(T/dt)
  integrated_x = np.zeros(num_samples)

  for sample in range(num_samples):
    x = np.zeros(timesteps)
    for time in range(1, timesteps):
      x[time] = x[time - 1] + dx(a, sigma, tau, dt)
    integrated_x[sample] = x[-1]
  w_std = np.std(integrated_x)
  return w_std

a_values = np.linspace(0, 0.1, 5)
w_std_list = []
np.random.seed(0)
num_samples = 1000

for a in a_values:
  std = w_process_numpy(num_samples, a)
  w_std_list.append(std)

#plot std in w as a function of mean (a)
plt.plot(a_values, w_std_list)
```

We would appreciate feedback on what we might be implementing/conceptualizing wrong and the reason for these discrepancies.

Thank you very much in advance,

Albert

**Comment by mstimberg** [comment]
Hi @albertalbesa. I have to say you got me worried there for a moment :-) Fortunately it turns out that everything seems to be working as intended. The reason you are seeing the dependency on `a` is that your `network_operation` is executed with a period of `T`, but this includes the very first time step at 0s! All your `brian_integrated_x` arrays therefore include a 0 at the beginning and overestimate the real standard deviation. This overestimation is stronger for bigger drifts, since the end values vary around higher absolute values.
As a general remark (even though I can imagine that the reason for your setup also has to do with your real, non-toy model application):  It is much faster to run a network with many neurons in parallel (one for each sample), instead of having a single neuron and resetting it regularly. Incidentally, you wouldn't have run into the issue this way either. Here's a code that even does a bit more, it runs a single network for all the samples and `a` values at once. This will run in under a second (with the default code generation, compilation will probably take longer than the actual run, feel free to switch it off via `prefs.codegen.target ='numpy'`):
```Python
from brian2 import *

defaultclock.dt = 0.5*ms

T = 1*second
num_samples = 1000
num_a_values = 5
tau = 1*ms
sigma = 0.1


group = NeuronGroup(num_samples*num_a_values,
                    '''dx/dt = a/tau + sigma/sqrt(tau)*xi : 1
                       a : 1 (constant)''', method='euler')
group.a = 'i//num_samples*(0.1/(num_a_values-1))'
print(group.a[:10])
a_values = np.unique(group.a)
print(a_values)
run(T, report='text')

matrix = np.reshape(group.x, (-1, num_samples))
fig, axs = plt.subplots(1, 2)
axs[0].plot(a_values, np.mean(matrix, axis=1))
axs[0].plot(a_values, a_values*T/tau, ':')
axs[0].set(xlabel='drift a', ylabel='mean after 1s')
axs[1].plot(a_values, np.std(matrix, axis=1))
axs[1].plot(a_values, np.ones_like(a_values)*sqrt(T/tau)*sigma, ':')
axs[1].set(xlabel='drift a', ylabel='stddev after 1s')
fig.tight_layout()
plt.show()
```

The result seems to be what you expect (dotted lines are the analytical solutions)
![noise_drift](https://user-images.githubusercontent.com/1381982/142612302-53f76f1d-de9a-4a5e-ba5b-422044d6ee7d.png)
:

**Comment by albertalbesa** [comment]
Thank you very much for the fast response and spotting our silly mistake!

Also thank you very much for the advice on the setup.


It is clear now the source of the error.
