### ISSUE TITLE
MAX functions seem not to be used in equations

### ISSUE THREAD

**Issue by HotCoCoC** [brian-team/brian2#1376]
I want to define synaptic behavior using MAX functions
Such as
`S = Synapses(G, G,'w :1' ,on_pre='''v_post = max(v_post+w,0) ''' )`
And there is error :KeyError: 'The identifier "max" could not be resolved.'
Because I want to define Inhibitory neuron, w has negative numbers. And I don't want V to be a negative number. So what should I do.
I'm a newbie at Brain2 and computational neuroscience. Sorry to bother you if it's a simple question QAQ

**Comment by mstimberg** [comment]
[In the future, please direct questions or error reports where you are not sure whether it is "Brian's fault" to Brian's [discussion forum](https://brian.discourse.group), we try to keep the github issues for bugs and feature requests.]

Hi. Due to the way Brian works internally (code generation for C++ etc.), you cannot use arbitrary functions, but only those functions that Brian supports. Here's a list of these functions: https://brian2.readthedocs.io/en/stable/advanced/functions.html#default-functions
In your case, you can use `clip` function which is slightly more general than `max` since you can give a lower and upper bound. To only set a lower bound, you can use `inf` for the upper bound: `v_post = clip(v_post + w, 0, inf)`.
