### ISSUE TITLE
problem with NeuronGroup

### ISSUE THREAD

**Issue by rinatsaban-uni** [brian-team/brian2#1508]
hello, I'm trying to run a NeuronGroup function, and got this error. what might be the problem?

![image](https://github.com/brian-team/brian2/assets/160756665/2d7279a1-d757-4a1a-961d-aa1748aeaefb)

**Comment by mstimberg** [comment]
Hi @rinatsaban-uni, I've seen that you closed the issue so I'll assume that you found the problem. In general, for this kind of question our discussion forum at https://brian.discourse.group is a better place to ask. Oh, and while the problem was most likely an incorrect equation, we definitely need to improve these error messages!
