### ISSUE TITLE
Issue: Tutorial Part 1 documentation for StateMonitor

### ISSUE THREAD

**Issue by HarshKhilawala** [brian-team/brian2#1532]
![Screenshot from 2024-05-28 15-07-19](https://github.com/brian-team/brian2/assets/61461050/fb747724-b2e1-4e71-ac56-bb9537453273)

Issue with Tutorial Part 1, [Link](https://brian2.readthedocs.io/en/stable/resources/tutorials/1-intro-to-brian-neurons.html#)

For the above example, `record=True` parameter is passed to StateMonitor.

But according to documentation of StateMonitor class [here](https://brian2.readthedocs.io/en/stable/reference/brian2.monitors.statemonitor.StateMonitor.html#statemonitor-class) , 

`record` parameter is used to specify the index of a particular Neuron (in case of population of Neuron)

**Comment by mstimberg** [comment]
Hi @HarshKhilawala. Thanks for opening the issue! The tutorial is correct, but the class documentation of `StateMonitor` is missing the information that the record argument can either be one (or many) indices, or `True` to designate "all neurons". The [user documentation](https://brian2.readthedocs.io/en/stable/user/recording.html#recording-variables-continuously) describes this correctly, though.

**Comment by mstimberg** [comment]
Actually, I just realized that we have this information in the source code (see https://github.com/brian-team/brian2/blob/master/brian2/monitors/statemonitor.py#L105-L108), but for some reason this information doesn't show up on our documentation page. I'll look into this!

**Comment by thesamovar** [comment]
Actually a bunch of stuff isn't showing up there, examples, notes, etc. Is it like that on all our docs?

**Comment by HarshKhilawala** [comment]
Would you like me to create PR to fix it? I would be happy to do so.

**Comment by HarshKhilawala** [comment]
@thesamovar Nice to know you as part of Brian Simulator! What is git bisect?

**Comment by mstimberg** [comment]
"git bisect" is a great tool to find when a bug was introduced (or fixed), see e.g. https://www.git-tower.com/learn/git/faq/git-bisect/

In this case, it seems 0344b005 broke everything, but I am having a hard time seeing what exactly went wrong. One thing this commit did, was to delete the line that actually created the reference documentation. This has been fixed in #1474. But apparently, it did more, since adding the missing line gives you the reference back, but only in the impoverished version we are seeing now.
