### ISSUE TITLE
`np.allclose` fails on quantities with units

### ISSUE THREAD

**Issue by lkeegan** [brian-team/brian2#1546]
```
a = np.array([1,2,3]) * second
np.allclose(a,a)
```
gives

`DimensionMismatchError: Cannot calculate 1e-08 add [10. 20. 30.] us, the units do not match (units are 1 and s).`:

Notebook to reproduce: https://gist.github.com/lkeegan/e4768be9f20f7e6913e33c79d6a25b14

Would it be possible to wrap this function as you already do for many other numpy functions to work with units?

It looks like there is already similar functionality in the test utils:

https://github.com/brian-team/brian2/blob/daba4e7fd0685382ea578f87e62324482dd5ea37/brian2/tests/utils.py#L8-L30

Thanks!

**Comment by mstimberg** [comment]
Many thanks for the report @lkeegan, I agree that this should work. We will look into this (CC @SorinAlexB who is currently working on an update of our unit system).

**Comment by mstimberg** [comment]
Hi again @lkeegan. We realized that this function is actually working as intended, and I don't think we will provide another wrapper function. Numpy's `allclose` works with a relative and an absolute tolerance. The reason why it fails is that the default absolute tolerance is 1e-8, which does not have any units. We could wrap this function so that it always works, but this would mean that the tolerance would be 1e-8 in base units, but when you compare things in, say, µF, it wouldn't make much sense to have the absolute at 1e-8F, i.e. 0.01µF. So the solution would be to specify the `atol` parameter whenever you use `np.allclose`, e.g.
```python
a = [1, 2, 3] *second
print(np.allclose(a, a, atol=1*usecond)
b = [1, 2, 3)*ufarad
print(np.allclose(b, b, atol=1*nfarad)
```
Would that work for you?

**Comment by lkeegan** [comment]
Thanks, that's a good solution for me.
