### ISSUE TITLE
Raise errors for ambiguous synapse variables

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#348]
Working on @brian-team/brian2genn with @tnowotny we were thinking about the way pre/post/synaptic variables are referenced in synapse code. I think the current rule is that an unsuffixed name must refer unambiguously to either a postsynaptic neuron variable or a synaptic variable, with an error raised if there is a clash, but no error raised if there is a clash with a presynaptic variable. Perhaps we ought to be more rigorous here and raise an error if there is any clash and force the user to specify _pre, _post or _syn in this case?

**Comment by mstimberg** [comment]
This is something about which we should get feedback from @romainbrette, I'll ask him later. I was initially a bit worried that we used the "postsynaptic variable without suffix" syntax in the Frontiers paper but it turns out we only used the `_post` syntax there, so this is not a problem. If we decide to go with the unambiguous syntax (no suffix --> synaptic variable): should we have it raise an error immediately or should we do a soft transition with a `DeprecationWarning`? We used statements such as `v+=w` in quite a few examples... On the other hand, with the error message telling you what to do to make it work again, it shouldn't really be an issue.

**Comment by thesamovar** [comment]
I think we discussed this when I was in Paris and we decided to go ahead? I would say just make it an error and don't worry about ``DeprecationWarning`` but I'm not against having it if you think it's worthwhile.

**Comment by mstimberg** [comment]
We discussed this today and @romainbrette wasn't too fond of getting rid of the "`v` instead of `v_post`" shorthand. The compromise solution we could all live with was: raise an error if there is a clash and force the user to rename the synaptic variable but continue to allow to not use the `_post` suffix if there's no synaptic variable with the same name.
One remaining question: should we only do this for a clash between synaptic and postsynaptic variable or also for a clash between synaptic and presynaptic variable? In the latter case there's not really room for ambiguity, you can never just write the name of a presynaptic variable to refer to it. I think I'd therefore prefer to only raise an error for the name conflict synaptic-postsynaptic.

**Comment by thesamovar** [comment]
Strange: I thought we'd already talked about it and decided differently. I would say raise the error if there is any ambiguity at all (i.e. between pre, synaptic or post; including a clash between pre and post). We know that the user cannot write presynaptic variables without putting ``_pre`` but they don't necessarily know that.

**Comment by mstimberg** [comment]
I don't quite remember what/whether we decided back then but I'm fine with raising an error in all cases. Should we go ahead with this then?

**Comment by tnowotny** [comment]
I would think it's the cleanest solution - for the interface I certainly would need things translated to this explicit format anyway.

**Comment by mstimberg** [comment]
I just realized that we can't possibly raise an error for a conflict between pre and post, this would make connecting a group to itself impossible... Even if we'd only check it if the groups are not identical, it could make things annoying e.g. if you want to create a connection between groups that are created in other code, automatically created from NeuroML or whatever. I think we shouldn't raise any error on Synapses creation that you cannot deal with by changing stuff in the Synapses class creation.
So that leaves us with errors when there is a clash between synaptic variables and pre or post variables.

@tnowotny This discussion here is a bit unrelated to the GeNN problems (see the mail I just sent), this is only about the user syntax. Bascially, in the GeNN interface you should not have to worry about the names of variables any more. Brian already did all the parsing etc. and figured out what variable names mean at this stage, all relevant information is stored in the respective `Variable` object.

**Comment by thesamovar** [comment]
We only raise an error if there is an ambiguity. So you can connect a group to itself but in that case you have to specify ``v_pre`` and ``v_post``. Similarly, if you have a ``w`` in both your synapses and your group, you have to refer to ``w_syn`` or ``w_post``. At least, that's what I thought we meant.

**Comment by mstimberg** [comment]
Um, okay now this is getting confusing. We decided against adding another suffix `_syn`, what I thought we agreed on (at least that was my consensus with Romain) was that if you have a `w` in both your synapses and your group, then you get an error during creation time and you are forced to rename your `w` variable in the `Synapses` object (which of course could well be `w_syn`, we could even suggest this in the error message). And I think it will be quite common to have `v` in the pre and the post group (be it the same or not) so forcing the user to use `v_pre` and `v_post` in this case is almost equivalent to always force the use of the `_post` suffix (which @romainbrette wasn't happy with).

Just from the technical side: it's much easier to do all name clash checks at creation time (i.e. just check what variables are present in the connected groups and the synapses) than do something that is based on the use of the variable names in the strings. I don't quite see how we could raise a meaningful error about the incorrect use of a `v` variable at a later stage without building something synapse-specific into the code generation stage.

**Comment by thesamovar** [comment]
I'm happy not to use ``_syn`` and to force a different name for the Synapses variable instead. I'm not so sure about default to post when there is a clash between pre and post. What about having an info level warning when there pre/post conflict telling you that it is using post by default?

**Comment by thesamovar** [comment]
Also yes, I think it should be checked at creation time.

**Comment by mstimberg** [comment]
Ok, I think I'm fine with that. So to summarize:
* Clash between pre and synaptic or post and synaptic variable name: raise an error, force the user to rename the synaptic variable (and suggest to use name `_syn`)
* Clash between pre and post, log an info level message telling the user that the name of the variable without suffix will be interpreted as `_post`

I think using info level here (instead of a warning) is fine, it fits with the general approach we have (or at least: want to have) for info, which is that it tells about automatic choices made by Brian (automatic code generation target, automatic state update algorithm, ...).

One small thing about the info message: we only log one of them, not one per variable, right? Otherwise it would be quite a mess if you connect a group to itself.

**Comment by thesamovar** [comment]
I would say one per variable that is actually used, and I don't think it'll be a big problem because normally it will be just one (v).

**Comment by mstimberg** [comment]
This is what I meant before about the check at creation time: we don't know what will be actually used at this point, e.g. you could write `S.connect('...')` or `S.w = '...'` later which might refer to other variables, it's not enough to look at the arguments of the `Synapses(...)` initializer. 
I therefore think we should do a general error message (and maybe mention one example variable if there is more than one, we could even use our `guess_membrane_potential` utility function for that).

**Comment by thesamovar** [comment]
Ah I see what you mean. OK so how about we make it an error to have any shared variable names between all synapses and post-synaptic neurons (to get the best error at creation time), and info level warnings for pre/post clashes whenever they occur? Connecting a group to itself will be fine because we won't raise info level warnings for all clashing variables, only the ones that are actually used. Seems reasonable?

**Comment by mstimberg** [comment]
> and info level warnings for pre/post clashes whenever they occur?

that's the part we can't really do: at the point when a clash occurs, say you write `S.w = 'v'` (doesn't make much sense, but...) we go through the normal code generation pipeline with nothing synapse-specific in it. We have some code (`w = v`) and a dictionary of variables. I can't think of a straightforward check at this stage to raise a warning. The best I can think of would be something like "raise a warning if another name in the dictionary links to the same `Variable` object and has the same name + some suffix". But then this would also raise a warning for every use of `i` (which is the same as `i_pre`)...

**Comment by thesamovar** [comment]
How about adding a new attribute to variables ``.ambiguity_warning_if_used``, or maybe a better name. ;) This attribute could be added to all variables that could be ambiguous but only causes the warning to be shown when it is actually used. Any good?

**Comment by mstimberg** [comment]
Hm, maybe we can do something along those lines. We can't store it in the `Variable` object, though, since this is unique for a variable and shared among all groups. We'd have to have something stored in the group. Another problem is the time of the warning: for `pre` statements, for example, we do the variable resolution at the time of the run (since it could refer to external variables that are not set yet). It would be odd to get a warning at this point and not already at the time of the creation of the `Synapses` object...

**Comment by thesamovar** [comment]
We're only interested in conflicts between group variables though, right? So we should be able to determine that at the creation time.

**Comment by mstimberg** [comment]
> We're only interested in conflicts between group variables though, right? So we should be able to determine that at the creation time.

Yes, but it means we have to do write specific checks for that at creation time, it can't be part of the standard mechanism. I wonder whether all this effort is worth it just for telling the user that `v += w` refers to `v_post`, not to `v_pre`...

**Comment by mstimberg** [comment]
Actually, how about doing the error on clashes between synaptic and pre or post variables now, and postpone the decision/implementation of the clash between pre and post? Since the latter will probably be an info level warning, it also first needs a cleaning up of the current info level output and making it the default level.

**Comment by thesamovar** [comment]
Yeah I think it is worth doing, but I'm happy to postpone.

**Comment by mstimberg** [comment]
I opened a new issue for the warning (#406), let's close this issue as soon as the error message for synaptic vs. pre/post is implemented.
