### ISSUE TITLE
Add a binomial function

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#373]
This is needed for #221 and depends on #366

**Comment by thesamovar** [comment]
Where did we get with this?

**Comment by mstimberg** [comment]
I don't quite remember what we agreed to as a solution for the indirect call of numpy's rand function was. I think we have two options:
* Get completely rid of the call to numpy's rand function in weave, use the C implementation as in standalone (after #222 has been implemented)
* Use the alternative namespace approach for functions that should replace the `#define` hacking, as outlined in #380 

I think the second option would be better for now, we have to revise this mechanism to get a `TimedArray` implementation in Cython, anyway.

**Comment by thesamovar** [comment]
I think until we have a good solution to #222 we should be happy with "any decent RNG". Certainly numpy's rand function is good enough, and so would the simple implementation of MT that we discussed in #222, but not stdlib's ``rand()`` function. In terms of implementing it, I don't think we need to worry about having the same implementation in standalone as weave, and I agree with what we decided in #380 so that seems best.
