### ISSUE TITLE
Some old, some new = error?

### ISSUE THREAD

**Issue by epaxon** [brian-team/brian2#391]
Why can't the magic network just reset everything when there is a mix of some new objects and some old objects? Or is there a way to just get it to reset everything -- reinit() does not work anymore?

**Comment by thesamovar** [comment]
The reason is that we don't want to take action when it is ambiguous. You might expect it to reset everything: someone else might expect it to do something different. So, we try to minimise unexpected errors by not guessing.

The reinit function no longer exists in Brian 2, but there is a new way. At the beginning of your simulation, you call ``store()`` which stores in memory a copy of the current state of all the objects, and then you can rewind to that state by calling ``restore()``.

See http://brian2.readthedocs.org/en/latest/user/running.html#continuing-repeating-simulations for more.
