### ISSUE TITLE
Make `INFO` the default log level and clean it up

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#407]
As we discussed, INFO should be the default log level and as a general rule it should output all information that is "guessed" by Brian, examples:
* Objects included in a magic network
* If time is reset or continued (in a magic network)
* Maybe the dt that is used?
* Automatically chosen integration method
* postsynaptic variables without suffix (#406)
* maybe: all "resolution conflict warnings", e.g. you have an `N` variable in your script but a string expression refers to the internal `N` (which has a different value)
* anything else...?

About the resolution conflict warnings: we currently have a mechanism to selectively suppress some warnings (even I don't think anyone ever used them) -- should we have the same for all log levels, maybe? With the above, what would remain to be a warning? Maybe everything that is almost certainly a mistake, e.g. an empty network or a synapses object without synapses?

**Comment by thesamovar** [comment]
I would be wary of putting too much information on by default because we'll just train users to ignore it if we do that. I think the most important stuff that people should see by default is:

* Chosen integration method (unless it's exact or unless they specified it)
* Postsynaptic variables without suffix
* Resolution conflict warnings (unless there are too many of them in which case maybe just a short warning saying that there were resolutions conflicts and they should put a higher log level on to see them?)

The other stuff I would argue shouldn't be included by default. Maybe the times for the magic network runs, but even then I'd suggest against unless we have a reason to think that it might not be what is expected. So in the safe condition where e.g. it is the first run, or it is a second run with no change in objects, then we should not show it. In the unsafe conditions we could show it.

I would say the objects included in the magic network is not a good idea because in 90% of the cases, users won't give them names and so the names they see there will be just meaningless and confusing for them.

I don't think we need to list dt because by default we have a pretty safe value for that.

Are we going to need two different info levels now?! :)

**Comment by mstimberg** [comment]
I'm not sure that too much information is really a problem here -- the idea is that it's exactly the kind of information that you *should* ignore most of the time (everything else should be a warning) but which becomes helpful if the simulation does not do what the user wants (you don't have the log file if no exception was raised). I'm thinking of it as a "verbose" mode and I think most users actually want to have some output on the screen while Brian is doing all kind of stuff (in most complex simulations you have print statements showing the progress littered around). Somewhat related: I think we should make `report='text'` the default argument for `run`. I'm not 100% sure of whether this log level should be the default, but I'd really like to have one "verbose" mode with a reasonable amount of information. And I think the debug level is always too much (or we need two debug levels) and all these things are not really warnings, so info level seems to be the reasonable choice.

> Chosen integration method (unless it's exact or unless they specified it)

I only meant to show it when it is *automatically* chosen. I'm not sure we should make an exception for "exact", though.

> The other stuff I would argue shouldn't be included by default. Maybe the times for the magic network runs, but even then I'd suggest against unless we have a reason to think that it might not be what is expected. So in the safe condition where e.g. it is the first run, or it is a second run with no change in objects, then we should not show it. In the unsafe conditions we could show it.

For me, it should actually show the expected stuff -- as a confirmation that everything is working as expected. But certainly for the first run it is not very interesting. Maybe only when the time is reset automatically? On the other hand, after a `restore` it might be nice to see the time... Hmm, but maybe a much simpler solution would be to include the start time in the output of `run` with the report option (i.e. instead of "starting a simulation for 1s", print "starting a simulation from 1s to 2s" or something like that. Oh and I don't think we really have "unsafe" conditions anymore, they'd raise an error now.

> I would say the objects included in the magic network is not a good idea because in 90% of the cases, users won't give them names and so the names they see there will be just meaningless and confusing for them.

The names is probably too much, I agree. But maybe something like "5 objects" or "3 NeuronGroups, 1 Synapses, 1 StateMonitor"...?

> I don't think we need to list dt because by default we have a pretty safe value for that.

You are probably right. Or maybe mention it if there are several clocks? This could mean that a user changed `dt` for a single object instead of changing `defaultclock.dt`.

**Comment by thesamovar** [comment]
OK so maybe we will need a normal and a verbose info level (i.e. two levels between debug and warning). I'm not sure what the default should be though. I know that I'd always prefer to reduce verbosity because I like to have control of what gets printed since I often use printing in my code to get an idea of what's going on and it would get drowned out by the other stuff.

So if we had two levels then I'd say we put things at normal info level if we think that people ought to be aware that a significant choice has been made (i.e the things I listed in my previous post), and verbose info level for the list you made. What do you think?

> I only meant to show it when it is automatically chosen. I'm not sure we should make an exception for "exact", though.

I think we can make an exception for exact for the normal info level because with exact they couldn't have made a better choice. With any other integration method it might not be the best choice.

> maybe a much simpler solution would be to include the start time in the output of run with the report option

Yes that sounds good.

> The names is probably too much, I agree. But maybe something like "5 objects" or "3 NeuronGroups, 1 Synapses, 1 StateMonitor"...?

That's better. Not sure if that should go at normal or verbose level though. The full list of names is in debug already, right?

> You are probably right. Or maybe mention it if there are several clocks? This could mean that a user changed dt for a single object instead of changing defaultclock.dt.

We could maybe show it if the user is making use of both individual dt and defaultclock.dt. Actually, maybe that should be a warning actually?

> Somewhat related: I think we should make report='text' the default argument for run.

I'd say that it's a bit too much, but we could make report='text' the default argument if the log level is at verbose?

**Comment by mstimberg** [comment]
I'm hesitant to introduce a new log level (something that the Python logging docs discourage as well). Also, we shouldn't come up with a too complicated solution, I think most users won't care about at all about all this ;)
Here's what the Python logging tutorial says about the log levels and their meaning, I think we should follow that as closely as possible:

Level | When it's used
------ | --------------
DEBUG | Detailed information, typically of interest only when diagnosing problems.
INFO | Confirmation that things are working as expected.
WARNING | An indication that something unexpected happened, or indicative of some problem in the near future (e.g. ‘disk space low’). The software is still working as expected.

My preferred solution would be the following: we come up with a consensus around the use of WARNING and INFO levels and make INFO the default. For the DEBUG level, I think the current level is too verbose and we could maybe make it into what you had in mind for a "verbose INFO" level. For the even more verbose output (e.g. complete generated code snippets)), we use a specific log category (e.g. ending in `verbose`) and suppress such messages by default (for display on the console, they'd still be logged to the file). I think it would be nice if all the three levels, WARNING, INFO and DEBUG would be of use to users and not only "for us".

What do you think about this general approach?

**Comment by thesamovar** [comment]
I think on the basis of that, some of what we had decided to put on info level really ought to go on the warning level. For the choice of numerical integration method, for example, we don't know if "things are working as expected" or not (but I would also not say that really "something unexpected happened"). On the other hand, I don't find their 'info' level very useful. I don't usually want a confirmation that things are working as expected: I assume things are working as expected unless there's a message telling me otherwise.

Although the tutorial does say that custom levels should be avoided, I do think that we have a genuine category here of decisions that we don't know for sure whether or not they are a problem or not. Also, adding an extra verbose tag seems to have the same problems and is more hacky than just adding a new level, no? I'd say that we should have a new level, either VERBOSE between DEBUG and INFO (and we make INFO the default console level); or something like DECISION/CHOICE/NOTICE/ALERT between INFO and WARNING (and we make this the default console level). I think I'd go with the former because the name verbose is clearer.

Also, one minor problem with putting some information in the file only is that the file is currently not easily accessible unless there's an exception in which case you get the location of the file. We should have an easy way to switch to verbose mode on the console too maybe. Or a method that prints the location of the log file.

I don't think the current debug level is too verbose. It's for finding problems and the best way to do that is to have all the information and filter it out as you need. For example, the bit that I look at most often in the debug output is the generated code snippets and I think the same would be true for most users. (Incidentally, it might be nice to add the locations of the weave/cython generated files in the debug output. When I want access to those at the moment it is really annoying to find them.)

**Comment by mstimberg** [comment]
Just very quickly (also: no need to rush this, I think it is not essential to have right now):

> Also, adding an extra verbose tag seems to have the same problems and is more hacky than just adding a new level, no?

I wouldn't say it is, as we already have a mechanism in the logging system that allows you to suppress log messages with category names ending in a certain string and which by default only affects the console, not the file.

> I don't think the current debug level is too verbose. It's for finding problems and the best way to do that is to have all the information and filter it out as you need. For example, the bit that I look at most often in the debug output is the generated code snippets and I think the same would be true for most users.

We seem to have different ways of using it :) I never use the debug level because it always displays way too much information for my needs, I don't care about most of the intermediate steps even for debugging. I almost always insert a quick `run(0*ms)` and simply print the code of the `CodeObject` I'm interested in :)

**Comment by thesamovar** [comment]
Agreed we don't have to rush to decide. 

For debug, how about we move some of that information (not the generated code) to the verbose level? So verbose would become debug lite. 

What I don't like about having a verbose filter rather than level is that if you switch to debug then you wouldn't pick up verbose info, meaning that if you wanted everything then you'd have to make two changes instead of one.

**Comment by mstimberg** [comment]
This is still milestoned for 2.0, so let's have another go at it. Let's define some basic principles and see where that gets us. And re-reading the discussion, I don't find a better solution for the "verbose" stuff, so let's go with a new "VERBOSE" log level as you proposed.

Basics:

* the default log level is INFO
* all warnings and info messages should be avoidable, e.g. by choosing an explicit state update method, renaming variables, adding a `clock-driven` flag, etc.

WARN level:
Everything that is possibly/probably but not necessarily an error, or something that has a strong impact on performance, examples:
* Resolution conflicts for variable names
* using a `Synapses` object without synapses
* Including a monitor in the network, but not the object it records (actually, maybe we should raise an error here?)
* A `StateMonitor` without a `record` argument (actually, maybe just make this argument non-optional...?)
* An equation uses `unless refractory` but no refractory period has been specified
* Using no `event-driven`/`clock-driven` flag for a differential equation in `Synapses`
* Using numpy without scipy for a multicompartmental simulation (very slow)

INFO level:
Information about automatic choices that are relevant to the user, examples:
* state update algorithm (if not specified)
* code generation target (if not specified) -- not sure about this one, it should not be relevant to most users
* that's actually all that I can think of at the moment -- if we have a system that deals with potentially long-running computations like the exact state update and gives feedback to the user if a computation takes long, this should go here as well I guess

VERBATIM (or DIAGNOSTIC ?) level:
Information that helps the user to debug their Brian script (i.e. not for debugging the generated code), examples:
* [code generation target (if not in INFO)]
* The objects (or number of objects) in a network when the network is run
* The clocks/dts that were used (possibly only if if not all objects used the defaultclock)
* Possibly: The number of generated synapses in a "connect" call

For the `report` argument of `run` I see two possibilities:
* Make the default value log-level dependent (i.e. nothing for <=INFO, `'text'` for >=VERBATIM)
* Make `report='text'` the default, but have it not print to stdout but instead to the log with VERBATIM level

DEBUG level:
Information that helps to debug Brian itself, i.e. errors in the code generation, etc.

Does this sound reasonable?

**Comment by thesamovar** [comment]
Sounds great to me. Another option would be to swap the roles of DEBUG and DIAGNOSTIC: i.e. debug would be the user debug level, and diagnostic would be our (occasional) debug level. That way, the users don't need to know about the non-standard thing. Sorry if this was already suggested in our discussion, I didn't reread. ;)

**Comment by mstimberg** [comment]
Ah, you just mean name-wise, so "normal users" would switch on `log_level_debug` while we would do `log_level_diagnostic` or something like that? I am fine with that as well, though I doubt that many users are aware that `DEBUG` is standard while `DIAGNOSTIC` is not ;)

**Comment by thesamovar** [comment]
Exactly that. A few users would know about debug levels but I guess nobody but us will know about diagnostic level. :) But you're right, and I'm happy to do it either way. The key point is that your general categories of errors are just right I think.

**Comment by mstimberg** [comment]
Ok, I'm happy with using DEBUG for users and DIAGNOSTIC for us.
What do you think, where should  the code generation target go? And what solution do you prefer for the `report` keyword of the `run` function?

**Comment by thesamovar** [comment]
I wouldn't bother mentioning the code generation target at the default level, so I'd put that in debug. It seems to me that if it's automatic (default) then they'll be using the best available option anyway. If they've specified it, we don't need to tell them.

I think I would have just left report off by default, but maybe you're right it should be on if you're at debug level. I don't have a strong feeling about which of the two options for doing this is better, so whatever you think. As long as the user can specify it explicitly if they want it, that's fine.

**Comment by mstimberg** [comment]
I am almost done with this (in the `log_levels` branch), I'll open a PR soon.

> I think I would have just left report off by default, but maybe you're right it should be on if you're at debug level. I don't have a strong feeling about which of the two options for doing this is better, so whatever you think. As long as the user can specify it explicitly if they want it, that's fine.

I thought again about this, and I now think that mixing the logging and reporting in either of the two ways is not great. How about simply including debug output at the start and the end of the simulation, something like `Simulating network 'network' from 0.0 s to 5.0s` / `Done simulating network 'network' (simulation took 13.43 s)`?  The information is mostly redundant with the output of `report='text'` but it is the essential part of it (which is also nice for the log file).

**Comment by thesamovar** [comment]
Sounds good!
