### ISSUE TITLE
Use parallel nose testing?

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#451]
Seems like it would be good to speed up the testing unless there's some reason why it doesn't work?

**Comment by thesamovar** [comment]
Just needs adding ``--processes=-1``.

**Comment by mstimberg** [comment]
I think at some point this was problematic (because several standalone tests were writing to `output` or something like that) but now it should be fine. There's only one issue (and I think that is why I did not include it): it isn't compatible with the test coverage measurements. Since we have only single core (virtual) machines on travis/appveyor, I don't expect it to lead to any speedups there anyway, so how about enabling it by default but including a switch to turn it off (which we'll use on travis when we do the coverage measurement)?

**Comment by thesamovar** [comment]
Sounds good!

**Comment by mstimberg** [comment]
um, so actually `weave` is not guaranteed to run correctly in a multiprocessing setup... It uses a single database and concurrent access to that database can fail.

**Comment by thesamovar** [comment]
Ah, that's a shame. OK, so let's not worry about it then. It's a minor improvement. I'll close this issue.
