### ISSUE TITLE
Record at beginning rather than end by default?

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#452]
At the moment, we record variables with when='end' by default. However, the corresponding time is t, the start of the interval [t, t+dt) being computed. It might be more logical to record at the beginning of the interval, although this has some drawbacks. Firstly, it is backwards incompatible, although Brian 2 is a good time to make these sorts of changes. Secondly, it means that the last value recorded in a run of 100ms would be the value at 99.9ms instead of the value at 100ms. (On the other hand, the last time recorded is already 99.9ms, so there's already something counterintuitive going on there.)

@romainbrette

**Comment by romainbrette** [comment]
Indeed if t is recorded at the beginning, it would be more consistent that all other variables are as well (by default). The backwards incompatibility seems quite minor. The second issue doesn't seem critical because there will always be boundary effects either at the start or the end.

**Comment by thesamovar** [comment]
So shall we decide to switch to ``when='start'`` by default?

**Comment by romainbrette** [comment]
I'd say yes, unless Marcel has a different view.

**Comment by mstimberg** [comment]
> I'd say yes, unless Marcel has a different view.

I somewhat do, actually :) At least I think we shouldn't rush it. Here's some reasoning:
When you say:

> Indeed if t is recorded at the beginning, it would be more consistent that all other variables are as well

This is not technically speaking correct. `t` is not recorded at the beginning, it is recorded whenever the `StateMonitor` is active, i.e. by default in the `end` slot. The `t` value is constant during a time step and only increases between time steps. This is nitpicking, but it becomes relevant when equations depend on time. A simple example (instead of a non-autonomous differential equation I use a custom operation in the state update time slot):
```Python
input = TimedArray([0, 1, 2]*nA, dt=defaultclock.dt)
G = NeuronGroup(1, 'I : amp')
dummy_state_update = G.custom_operation('I = input(t)', when='groups')
mon = StateMonitor(G, 'I', record=0)
run(0.3*ms)
``` 
Now, as a user looking at the recorded `I` variable, I would expect this output:
```Python
>>> print mon.t[:], mon[0].I[:]
[   0.  100.  200.] us [ 0.  1.  2.] nA
```
which is what you get with `when='end'` currently. With `when='start'` you'd instead get:
```Python
>>> print mon.t[:], mon[0].I[:]
[   0.  100.  200.] us [ 0.  0.  1.] nA
```
which I think does look "off-by-one".

**Comment by thesamovar** [comment]
I appreciate your point, but this example feels less typical than the usual case, where even though we can make a technically correct argument for the current behaviour, it's clearly surprising to a typical user.

**Comment by thesamovar** [comment]
OK we agreed to do this.

**Comment by thesamovar** [comment]
Someone suggested an idea to me which might work. Each timestep, you record ``t+dt`` at ``when='end'``. The first time the object is run, you additionally record ``t=0``. Like this, no matter how many runs there are, you get consistent behaviour, and you always have the beginning and end. Thoughts?

**Comment by thesamovar** [comment]
@mstimberg what do you think of this solution in the last post?

**Comment by mstimberg** [comment]
Oh, I forgot about this issue (and to reply to the last point). I have to say that I'm not sure this is worth the complication. First of all, we'd have to store the fact whether the simulation has been run already in a "proper" state variable, so that it works across `store`/`restore` calls. Secondly, we'd have to insert a specific code object that is executed once in the `before_run` method (if it is the first time that the object is run) and generalize the template so that it can record `t` or `t+dt` depending on some flag. And then, what if someone sets `when` to a different value -- will we still record `t+dt`?

Given that all this is non-trivial and non-obvious, I'd prefer to just go for `when='start'` -- it's not ideal because we are not recording what was simulated in the last time step but it is straightforward and easy to explain.

**Comment by thesamovar** [comment]
OK, I'm convinced. Should we have a method for recording the last time step or not? It could be pure Python I think (i.e. just a convenience method).

**Comment by mstimberg** [comment]
Um, I just checked, a method as simple as this would even work for standalone:
```Python
    def record_now(self):
        self.codeobj()
```
It *almost* works for the opposite use case as well (use when='end' and call it before the normal run), but in this case you'll end up with two values with the time stamp 0...

**Comment by thesamovar** [comment]
Cool! Let's have that then?

**Comment by mstimberg** [comment]
Yeah I think that's good (any better idea for the method name?), will add it soon and open a PR.

**Comment by thesamovar** [comment]
``record_now()`` works for me. Another alternative could be ``record_single_timestep()``.

**Comment by mstimberg** [comment]
Maybe that's better, it's explicit and self-explanatory.
