### ISSUE TITLE
Include sphinx conf.py in pypi tarball

### ISSUE THREAD

**Issue by sanjayankur31** [brian-team/brian2#453]
I was just trying to build Brian2 from pypi. Since conf.py isn't included, the docs can't be built. Can you please include conf.py in the tarball pushed to pypi? Alternatively, you could drop the docs from the tar if you don't want users building them. Having them there but not being able to build them isn't nice :)

The docs don't seem to build without the examples. Can these please be included too? Previously, I think there was a separate tarball for all the docs.

**Comment by mstimberg** [comment]
Hi, thanks for notifying us! I'll look into this, the next release should include buildable documentation.

Just in case you weren't aware of it: you can find the documentation (including the documentation for the latest development version on github) here: http://brian2.readthedocs.org
We no longer provide a separate archive for the docs, since readthedocs does the same for us automatically, you can download a zip archive of the HTML docs if you open the box on the bottom left on the documentation page.

**Comment by sanjayankur31** [comment]
Great, thank you. I was building a package to submit to Fedora, and I thought it'd be a good idea to build the docs and provide them in the repos too - for offline use. I've just used a git checkout of the latest release for the time being.

**Comment by mstimberg** [comment]
Ah, cool. I agree, a typical approach would be to have a separate `brian2-docs` package with the documentation in that case.
