### ISSUE TITLE
Unexpected behaviour of units with inline operators

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#469]
```
a = b = 1
b += 1
print a, b
a = b = 1*second
b += 1*second
print a, b
```

gives

```
(1, 2)
(2*second, 2*second)
```

This is a bug that actually bit me and I think the difference between Python standard behaviour here is a problem. The reason it happens is that ``1*second`` is actually an array so inplace operations modify the underlying data rather than rebinding the name. I don't think there's anything we can do about this is there? Could we raise a NotImplementedError for inplace operations for scalar values only and force it to go back to the Python default implementation (i.e. ``a+=b`` is ``a=a+b``)? If not, I think we probably need a big warning about this in several places in the documentation. What do you think?

**Comment by mstimberg** [comment]
I'm sure I discussed this issue before, but I can't find any email about it. I don't see any easy way to fix this "properly", i.e. make something like `3*ms` a scalar instead of a 0-size array. For this, I guess we'd have to have separate classes for scalars and arrays (as in numpy), which could possibly derive from a common class but still it would involve quite a bit of extra code and work.

So I think the approach to do a check when applying in-place operators is the easiest. I think we have two options that are both relatively easy to implement: raise a `NotImplementedError` for in-place operations on scalars (as you suggested) or use copy-semantics for scalars.

I guess the first is more consistent with our general "be explicit" approach but on the other hand the latter could be more user-friendly -- is there any situation where you'd actually expect this to work with reference-semantics like for an array?

**Comment by thesamovar** [comment]
I'm not sure I fully understood that. What would 'copy semantics for scalars' involve exactly? The ideal solution would be that for the user it behaves just like a float. I don't think you ever want them to behave like arrays because it's not what happens in normal Python.

**Comment by mstimberg** [comment]
> What would 'copy semantics for scalars' involve exactly?

This is what I think you have in mind. Currently, `+=` is implemented basically like this:
```Python
def __iadd__(self, other):
    self.add(other)
    return self
```

what I mean with "copy semantics" is to instead do this (only for scalars, though):
```Python
def __iadd__(self, other):
    result = self + other
    return result
```

I wouldn't mind that approach, but it means that `np.array(3)` and `np.array(3) * mV` would not behave the same in this regard (but currently `3` and `3*mV` don't behave the same which is certainly worse). We should then also assure that e.g. `3*mV/mV` does return `3` and not `np.array(3)`. 

BTW: the `quantities` package does the same as we do currently in Brian2 (but of course that does in no way imply that we should keep doing it):
```Python
>>> import quantities as pq
>>> x = 3*pq.mV
>>> y = x
>>> x += 1*pq.mV
>>> x
array(4.0) * mV
>>> y
array(4.0) * mV
```

**Comment by thesamovar** [comment]
Hmm, that is complicated. My feeling is that copy semantics (i.e. like python float) are better, but if it will introduce problems because of incompatibility with numpy scalar arrays then we could go with a warning.

**Comment by mstimberg** [comment]
Coming back to this: Maurizio recently stumbled across this as well, so it's not only you :) I don't see a way how we can do a warning without being annoying... The problem is that a `x += 1*mV` is fine most of the time under either interpretation, it only matters if there was an `y = x` before but we can't detect this situation. I'm fine with just silently (i.e. without warning but of course documented) changing the behaviour -- anyone that wants to treat a scalar as an array with reference semantics will just have to use `x = [1]*mV` instead of `x = 1*mV`.

**Comment by thesamovar** [comment]
OK. I'm also fine with silently changing the behaviour and making people use a size 1 array if they want reference semantics.
