### ISSUE TITLE
Exact integration not being used when refractoriness is on

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#560]
For example, in the CUBA example. I think this is because of boolean variables being non-constant and therefore making exact integration fail, but not sure about the long term consequences of that. Perhaps all integers and booleans could be considered 'constant' as far integration is concerned because they are never updated by state updaters. That's the critical thing right, not that it's constant but that it has no dynamics under the control of the integrator?

**Comment by mstimberg** [comment]
I think you are right, checking for "constant" values is not the correct thing to do. Actually, I think we can remove the complete check for constant values (references to `t` will be checked by the "locally constant" check). All variables that are not the variables defined by the differential equations are and should be considered constant over a time step, this already includes integers and booleans (which can't be differential equations). I guess I put in the check for constant values because Brian 1 had it, but the situation was different there since it pre-calculated a coefficient matrix (which of course needs constants) whereas here we are solving everything symbolically. Since it is somewhat related, how about adding this change to #534 ?

**Comment by thesamovar** [comment]
Yes, could you do that since you know that code better? I just finished making a couple of changes to #534.

**Comment by mstimberg** [comment]
Ok, will do.

**Comment by mstimberg** [comment]
I am waiting with the commit a bit until appveyor is finished with its current run -- otherwise it will get cancelled and we will have to wait longer for the standalone error messages...
