### ISSUE TITLE
Use homogeneous delays even if user doesn't give an explicit homogeneous delay

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#561]
I mean in those cases when the user doesn't say anything about delays: at the moment it uses the variable delay mechanism which is much less efficient.

**Comment by mstimberg** [comment]
Hmm, so this would be a syntax change, right? You'd have to explicitly specify something at construction time (e.g. like in Brian1: `Synapses(..., delay=True)`)?

From the user point of view it would probably be better to do a check whether the delays are homogeneous, so that these two things would do the same:
```Python
syn = Synapses(..., delay=2*ms)

syn = Synapses(..., delay=None)
syn.delay = 2*ms
```

But this is actually a bit tricky, since depending on whether we have homogeneous delays or not we store things in a different data structure (scalar array vs. dynamic array).

**Comment by thesamovar** [comment]
I was hoping we could do it without a syntax change. We'd check in before_run that len(unique(delays))==1 and if so use the homogeneous version.

**Comment by mstimberg** [comment]
Ok, right. It can't really be in `before_run` because of standalone, I think (without having had a look at it), the `initialise_queue` template (or corresponding function in `SynapticPathway` for runtime), or the initialisation function of the `SpikeQueue` would be the correct point for the check.

There would still a small difference between the two ways of constructing synapses with homogeneous delays I mentioned above: the second one will use more memory. But I think this is fine, the runtime is really the important issue.
