### ISSUE TITLE
Append works by-name instead of by-value with units

### ISSUE THREAD

**Issue by martinosorb** [brian-team/brian2#565]
I just realised that the behaviour of python's built-in list.append() method is not what I would expect when using variables that come with a unit:
the following code
```python
def spiketrain_nodim():
    events = []
    t = 0
    while t < 0.3:
        events.append(t)
        t += 0.1
    return events

print spiketrain_nodim()
```
prints `[0, 0.1, 0.2]`, whereas

```python
from brian2 import *

def spiketrain():
    events = []
    t = 0 * second
    while t < 1 * second:
        events.append(t)
        t += 0.1 * second
    return events

print spiketrain()
```
returns `[300. * msecond, 300. * msecond, 300. * msecond]`.

This is because the variable `t` gets appended by-name and not by-value, so all the changes to `t`affect the content of all the entries of the list. I suspect this is not the desired behaviour.

**Comment by mstimberg** [comment]
Hi. The problem is not so much the `append` but the `+=` operation and scalar arrays in numpy (if you use `t = np.array(0.0)` in your `spiketrain_nodim` function you will have the same issue. But you are not the first one that stumbled over these semantics and we did therefore decide to change this in the latest Beta release (2.0b4), so updating should solve your problem. See #469 and the bit in the release notes about in-place modifications: https://brian2.readthedocs.org/en/2.0b4/introduction/release_notes.html#important-backwards-incompatible-changes
