### ISSUE TITLE
Additional units

### ISSUE THREAD

**Issue by romainbrette** [brian-team/brian2#574]
For concentrations, the standard unit is molar (M). It's unfortunately not an ISI unit, as it's mol/liter. However in physiology one generally uses mM, which is `mol/m**3`. So maybe we could add mM as a unit? If it doesn't make sense, then we could just have it as shorthand for `mol/m**3`.
Speaking of which: mol could also be added, as it's the standard abbreviation of mole.
Also it seems that we don't have kelvin (temperature).
Finally, how about liter/litre?

Could we also have a few useful constants?
e.g.:
R (gaz constant)
F (Faraday constant)
There's of course the issue of how to name them (no so sure).

**Comment by thesamovar** [comment]
When we do ``from brian2 import *`` I think we should only have unit names that are safe, i.e. no one letter names. What about something like ``from brian2.constants import R, F`` so that you have to explicitly say which constants you want? For molar I didn't quite follow it, but I don't think we should add non-SI units: so writing ``mM`` as a shorthand for ``mol/m3`` seems like the better solution to me.

**Comment by romainbrette** [comment]
Yes absolutely. Your idea for constants is good.
For molar and others: yes I agree; we could have molar, mM, and uM as shorthands.
The only thing I'm wondering is for specifying units in equations: would mM work? (if not I think it's ok to have mol/m3)
How about kelvin?

**Comment by mstimberg** [comment]
All this was implemented in #821
