### ISSUE TITLE
Standalone build problems with MSVS 2015

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#607]
See #606 for background. We get a bunch of undeclared identifier errors for some reason (but only when using OpenMP).

**Comment by mstimberg** [comment]
I installed Visual Studio 2015 in my Windows VM and I can reproduce the error, I'll have a look, hopefully it is easy to fix.

**Comment by mstimberg** [comment]
I don't understand at all what is going on, I guess I'll ask this on stackoverflow if you don't have any idea either. I manged to reduce the issue to the following minimal example:
```C++
#include<omp.h>
namespace mynamespace
{
	double var;
}

void foo()
{
	using namespace mynamespace;
	#pragma omp parallel
	{
	}
}

void bar()
{
	using namespace mynamespace;
	var = 1.0;
}
```

If I compile this with `/openmp`, I get (line 18 is the line with `var` in `bar`):
```
minimal.cpp(18): error C2065: 'var' : undeclared identifier
```
Compiling it without OpenMP or without the parallel block or if `foo` and `bar` change place(!), works...

**Comment by thesamovar** [comment]
Ok so that must surely be a MSVC bug?

**Comment by mstimberg** [comment]
I think so too, but I would have expected that it breaks many peoples' code so that the internet is full of reports of this issue but I did not find any. Having said that, I just found one, it uses a minimal example that looks very similar to mine: https://connect.microsoft.com/VisualStudio/Feedback/Details/2094547

I also just learned that a new version of VS 2015 came out just a week ago, so it is possible that the issue has been introduced only then.

**Comment by thesamovar** [comment]
Looks like it. How about we just disallow the combination MSVS15+OpenMP rather than disallowing MSVS15 entirely? Hardly anyone is ever going to see this problem like that.

**Comment by mstimberg** [comment]
Yes, sounds like a good idea.

**Comment by mstimberg** [comment]
According to
https://connect.microsoft.com/VisualStudio/Feedback/Details/2094547
this has been fixed with "Update 2" of Visual Studio, which has been released on March 30th:
https://www.visualstudio.com/en-us/news/vs2015-update2-vs.aspx

We should therefore remove the workaround I think (the version of VS 2015 on appveyor also has this update: https://www.appveyor.com/docs/installed-software#visual-studio-2015)

**Comment by thesamovar** [comment]
Yep, I'm fine with that.
