### ISSUE TITLE
Update examples to specify method to avoid info notices?

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#663]
Or don't show method choice for method=linear?

**Comment by mstimberg** [comment]
I noticed it as well and it becomes a bit annoying quickly...

> Or don't show method choice for method=linear?

I would not do that because this is actually the use case where we *should* show it -- if the model setup takes crazily long, it is often because calculating the exact solution took a long time.

Maybe let's just demote it to a `DEBUG` message... Um, do we have any other `INFO` level message actually? Alternatively, I think always specifying the method is not bad either, it certainly makes it more explicit.

**Comment by thesamovar** [comment]
What about we only show the info message if the method choice takes more than 1s? I think that makes sense.
