### ISSUE TITLE
More efficient random number generation for cython/weave

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#667]
I think it should be possible to do better than the current buffering solution by using some of the ideas from these pages:

https://groups.google.com/forum/#!msg/cython-users/9UGMi_b3tVo/XhQinHU6NswJ
https://groups.google.com/forum/#!topic/cython-users/3bHwuwTfSkU
https://github.com/stefanv/lmwang_cython
https://bitbucket.org/joshayers/cythonlib/src/c42594d80cc448dbc7da9e9da86dab8dbc45c07f/cythonlib/?at=default

Essentially rebuilding numpy's C-based RNG which is actually not that complicated code and then using direct access to these functions. Would also work with standalone. Here's the source code (there are a couple of other files too):

https://github.com/numpy/numpy/blob/master/numpy/random/mtrand/randomkit.c

I've put this as 2.0 for the moment since we decided we wanted to do this better for standalone at least, and actually it looks like it might not be too difficult to do it well and consistently for standalone/weave/cython/numpy.

**Comment by thesamovar** [comment]
By the way I started looking into this while doing performance testing for #600, and realising that the numpy ``rand()<p`` was about twice as fast as the Cython code for ``p>0.25`` even though the Cython code was falling back on doing essentially ``rand()<p`` in this range (but it was doing ``_rand()<p`` where ``_rand`` is our hacky buffered access to numpy's ``rand``).

**Comment by mstimberg** [comment]
I think for runtime it is not a high priority for now, but as we discussed, we should hack something better than the stdlib rand for standalone. In the long run, I'd like to use something like this random number generator everywhere: http://dl.acm.org/citation.cfm?doid=2063384.2063405 This will be especially useful for OpenMP, CUDA, etc.

The problem with our hacked-together buffer solution is that it uses a fixed buffer length instead of something adapted to the problem (this is also the problem behind the fact that you cannot reproduce random numbers in the same process with weave, even after resetting the seed). I think in general parameterless functions like `rand` should not only get the `_vectorisation_idx` parameter, but two parameters, something like `_vectorisation_idx, _vectorisation_size` and possibly even a third argument, something like a unique identifier for the random number stream to deal with reproducibility with several noise variables (see #19). Maybe it is worth doing it for 2.0 (certainly not for the release candidate, though) -- let's make this the only major issue for after the RC, though ;)

**Comment by thesamovar** [comment]
For standalone this is done (not tested for Linux yet, only Windows): see PR #671.

I think the same approach can be modified to work for weave/cython but there are some issues (see discussion there).

**Comment by mstimberg** [comment]
During discussion in #671 we decided to stay with the buffering solution (although there is potentially room for improving the performance, see #711), therefore we will not implement what was discussed here.
