### ISSUE TITLE
SpikeMonitor.spike_trains returns spikes out of order

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#725]
If you use ``t=SpikeMonitor.spike_trains(i)`` then ``t`` will not be in sorted order. It seems that we use some slightly strange code in ``EventMonitor.values`` with ``unique`` that isn't guaranteed to respect order.

**Comment by mstimberg** [comment]
Yikes, we should have a test for that! The recorded data should already be ordered by time (at least for each index) so possibly replacing:
```Python
sort_indices = np.argsort(indices)
```
in `EventMonitor.values`
by
 ```Python
sort_indices = np.argsort(indices, kind='mergesort')
```
is already enough (the default sort algorithm is not stable). Or maybe we should sort on index + time to be safe?

**Comment by thesamovar** [comment]
I think using a stable sort should be fine, and numpy does guarantee mergesort to be stable.

**Comment by mstimberg** [comment]
I tried to write a test case that fails for current master, but I did not manage to generate out-of-order spike trains. Did you observe this problem under any particular circumstances (e.g. C++ standalone with OpenMP)

**Comment by thesamovar** [comment]
Versions were: python 3.5.1 Anaconda 4.0.0 numpy 1.10.4 brian 2.0rc3. Not sure which codegen target but definitely not standalone (so I don't think it's an OpenMP thing).

**Comment by thesamovar** [comment]
Windows, probably 64 bit.

**Comment by mstimberg** [comment]
Um, it turned out that I couldn't trigger the bug because my example list was too short -- numpy's quicksort implementation switches to insertion sort for partitions < 15 elements, so the sorting was necessarily stable. I searched slightly longer random sequences until I found one that leads to an unstable sort and as expected, recording such a sequence with `SpikeMonitor` led to the bug you observed. I pushed the fix and I'll open the PR in a sec.
