### ISSUE TITLE
Add support for more compilers etc.

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#757]
E.g. Intel compiler, MKL library, etc.

**Comment by thesamovar** [comment]
Nobody has ever asked for this - closing.

**Comment by thesamovar** [comment]
If you think you might one day work on it - happy for you to re-open the issue.

Agreed that when using things like linear algebra and FFT, MKL can make a big difference, but we're not doing that any more in Brian and I don't think we have a plan to.

**Comment by mstimberg** [comment]
I'm fine with leaving it closed for now, I don't think I'm going to work on this anytime soon. The only place where I could imagine it having a significant effect would be the propagation calculation in `SpatialNeuron` because there we are using some linear algebra. But it would be a bit of work to rewrite things so they can be handed over to a library function.
