### ISSUE TITLE
PoissonInput doesn't work with refractoriness and numpy target

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#761]
```
from brian2 import *
prefs.codegen.target = 'numpy'

tau = 10*ms
eqs = '''
dv/dt=-v/tau : 1 (unless refractory)
'''
G = NeuronGroup(100, eqs, reset='v=0', threshold='v>1', refractory=1*ms)
P = PoissonInput(G, 'v', 10, 100*Hz, weight=0.1)
run(100*ms)
```

gives the error:

```
BrianObjectException: Original error and traceback:
Traceback (most recent call last):
  File "E:\Dan\programming\brian2\brian2\codegen\runtime\numpy_rt\numpy_rt.py", line 122, in run
    exec self.compiled_code in self.namespace
  File "(string)", line 13, in <module>
ValueError: operands could not be broadcast together with shapes (99,) (100,) (99,) 

Error encountered with object named "neurongroup_1".
Object was created here (most recent call only, full details in debug log):
  File "<ipython-input-2-ff5506ac93b4>", line 9, in <module>
    G = NeuronGroup(100, eqs, reset='v=0', threshold='v>1', refractory=1*ms)

An exception occured during the execution of code object poissoninput_1_codeobject.
The error was raised in the following line:
v[not_refractory] += 0.1 * poissoninput_binomial_1(_vectorisation_idx)
 ValueError: operands could not be broadcast together with shapes (99,) (100,) (99,) 
(See above for original error message and traceback.)
```

The line with the error should probably read:

```
v[not_refractory] += 0.1 * poissoninput_binomial_1(_vectorisation_idx)[not_refractory]
```

So I think this is an issue with the numpy codegen path rather than `PoissonInput` itself.

**Comment by mstimberg** [comment]
I had a quick look at it and as you say it is a general numpy codegen problem not something specific to `PoissonInput`. I think you can trigger it whenever you use an automatically vectorized function (e.g. `rand()`) in combination with an `unless refractory` variable. E.g. the following code triggers it as well:
```Python
from brian2 import *
prefs.codegen.target = 'numpy'

G = NeuronGroup(10, 'dv/dt = -v/(10*ms) : 1 (unless refractory)',
                reset='v=0', threshold='v>1', refractory=1*ms)
G.v[:5] = 1.1
S = Synapses(G, G, on_pre='v += rand()')
S.connect(j='i')
run(defaultclock.dt)
```

So the problem is that `_vectorisation_idx` refers to "all neurons/synapses" (where "all" could be "all that received a spike, i.e. depends on the context) and in numpy we therefore generate the respective amount of random numbers. We could throw away some of them (this would be more or less what you propose above), but I think the correct solution would be to not generate too many numbers in the first place. This will also become important at some point if we become more strict about random-number reproducibility across code generation targets.

The fix is a bit complicated by the fact that in numpy, `_vectorisation_idx` can be either a number or an array of indices. In the first case we use the number directly to know how many random numbers we should create, in the second case we take the length of the array. In the context of what the `_vectorisation_idx` is supposed to be in the long run (again, for random-number reproducibility), only the array is "correct". But for obvious reasons we did not want to include code such as `_vectorisation_idx = np.arange(N)` for each loop over neurons.
I think we should get rid of the shortcut of using numbers instead of arrays for `_vectorisation_idx` in numpy. The cleanest solution I see is to have a simple "arange wrapper" that has a `__len__` method, i.e. you can treat it as an array but it does not store any numbers internally.

This was a bit of a detour, but if we have the above situation, i.e. that `_vectorisation_idx` is something array-like, then I think the correct fix for the bug here would be to explicitly deal with it like this:
```Python
v[not_refractory] += 0.1 * poissoninput_binomial_1(_vectorisation_idx[not_refractory])
```

**Comment by thesamovar** [comment]
arange wrapper trick sounds like a good idea if it can be made robust.
