### ISSUE TITLE
Izhikevich neuron model issue

### ISSUE THREAD

**Issue by balou1902** [brian-team/brian2#809]
Good morning,

I would like to simulate Izhikevich neuron model on Brian2 but I am new python language user (first time I have used it) and thus, I meet some difficulties. 

Here's my code : 
start_scope()

Parameters of Izhikevich model
a = 0.02/ms 
b = 0.2/ms
c = -65*mV  # resting potential
d = 8*mV/ms

eqs = '''
   dv/dt = (0.04/ms/mV)*v**2+(5/ms)*v+140*mV/ms-u + I : volt
   du/dt = a*(b*v-u) : volt/second
   I : volt/second
'''
Reset of Izhikevich model
reset ='''
v = c 
u += d
'''
Population of neuron(s)
G = NeuronGroup(1, eqs, threshold='v > 30*mV',reset=reset, method='euler')
M = StateMonitor(G,'v',record=True)

run(500*ms)

figure
plot(M.t/ms, M.v[0])
xlabel('Time (ms)')
ylabel('v');

I obtain the figure 1.
![figure_1](https://cloud.githubusercontent.com/assets/21360942/22546167/3b0ceeca-e93c-11e6-9d2e-c2d5f4351ef4.png)

I have some questions...
1. What's the value of I ? I mean... How does Brian2 manage to estimate v without the value of I ?
2. Why do I have only 1 spike  in the whole time of simulation ?

Sorry if the answers seem obvious but like I said, this is the first time I have used python.

Thanks you very much.

**Comment by mstimberg** [comment]
Hi and welcome to Python/Brian :)
Questions like this are better suited for our support mailing list (see http://brian2.readthedocs.io/en/stable/introduction/support.html) -- we use the github tracker to deal with bugs/missing features in the software itself.
The initial values of all state variables (in your example, ``v``, ``u``, and ``I`` are the state variables of your model) are 0, you therefore get an spike in the beginning because 0mV is above the threshold for the membrane potential. After that, because you don't inject any current (I = 0V/s), nothing is happening anymore.
By assigning to `G.v ` (e.g. `G.v = c`) you can set the initial value for `v`, equivalently for `I`. See the docs  (http://brian2.readthedocs.io/en/stable/user/models.html#state-variables) for more details. Also, please do have a look at our tutorials, they explain this and plenty of other things:
http://brian2.readthedocs.io/en/stable/resources/tutorials/index.html
