### ISSUE TITLE
Decide about package versions/dependencies (for testing and conda)

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#825]
With the merge of #821, I have introduced a few workarounds/quick fixes that might be worth discussing. They are about several incompatibilities with several package dependencies, in particular `cpuinfo`.

The main changes:

1. We test and build conda packages for Python 3.6, but no longer for Python 3.4
2. We build conda packages for numpy 1.12 but no longer for 1.9
2. On Python 3, we install scipy==0.18 instead of the latest 0.19 version because that comes still with weave
3. For Python 3.6, we don't test/build packages for linux-32

A lot of this is due to the `cpuinfo` dependency. I added this package to conda-forge (https://github.com/conda-forge/py-cpuinfo-feedstock), but this does not create packages for Python 3.4, nor for linux-32 bit. Also we don't have numpy 1.9 packages for scipy 0.19.

I guess one simple change that we should make is to make `cpuinfo` only a dependency for Windows, not for Linux/OS-X (we only use it to determine the best arguments for msvc). Then, for the conda packages, I think it is perfectly fine to only support a restricted subset (e.g. no Python 3.4, no numpy 1.9) -- after all, if you already use anaconda, you can easily upgrade packages. Users can always install from source if necessary. The only question is whether we should continue to test older versions or not.

Finally, dropping linux-32 support wouldn't be a big deal, it currently makes up only 0.8% of our downloads. Oh and about weave: I proposed the addition of a conda package to conda-forge (conda-forge/staged-recipes#2617). As soon as we have this package, we can drop the scipy workaround.

**Comment by thesamovar** [comment]
I'm not against dropping 3.4 support, nor older numpys and linux-32, although I'd only do it if necessary so I'd prefer another approach if possible. If it's just about the py-cpuinfo then I'd happily drop this as a strict dependency and use non-optimal settings if it's not installed, or have it as Windows only. Is there a way to say a package should be installed if possible, but isn't required? It would be a shame to totally eliminate it from the dependencies because then presumably hardly anyone will have it installed and won't get the benefits.

**Comment by mstimberg** [comment]
This is completely outdated and no longer relevant
