### ISSUE TITLE
Reinitialize StateMonitor class

### ISSUE THREAD

**Issue by jsdessureault** [brian-team/brian2#845]
Hi,

I am running a spiking neural network in real time.  The simulations are in an infinite loop.  
My problem is that the data recorded in my StateMonitor are not resetting after each simulation. 
The reinit method is not implemented yet.  
And then my StateMonitor result is growing and growing after each simulation, until it has no memory and stops. 
The function RecentStateMonitor is no more available since Brian 2. 

Any idea?  

In advance, thanks!

J.Sebastien

**Comment by mstimberg** [comment]
Just to make sure that I understand: you want to continue a previous simulation, but start with an empty `StateMonitor` (if you wanted to start a whole simulation from scratch, you should use the `store`/`restore` mechanism), correct?
The simplest solution to this is to create a new `StateMonitor` and throw out the old one (using `Network.add`/`remove`. Another solution would be to use Brian's extension mechanisms to create an equivalent of `RecentStateMonitor`, but I'm not sure this is worth the effort here.

In general, I'd recommend to ask questions like this on the mailing list (http://groups.google.com/group/briansupport) instead of in a github issue.

**Comment by jsdessureault** [comment]
Ok, thanks!  
That was it.  I just use Network.add and .remove to start a new monitor.  It did not work without it. 
Next time I'll go to the Google group Brian support.  Sorry for this time. 
Best regards!
JS
