### ISSUE TITLE
Boolean synaptic variables don't work with standalone

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#885]
The reason is that it tries to create a ``std::vector<bool>`` which (annoyingly) in C++ is treated differently to ``vector<dtype>`` for all other dtypes. With bool, you cannot get a pointer to an item because 8 items are packed into each byte. We solved this elsewhere with ``vector<char>`` for boolean, but apparently it's not working in standalone at least.

**Comment by mstimberg** [comment]
Do you have a concrete example where it does not work? We supposedly fixed this a couple of years ago (#319), specifically for standalone, and there is a test (`test_storing_loading()` in `test_cpp_standalone.py`) that at least checks the basic use of a boolean synaptic variable.

**Comment by thesamovar** [comment]
Following code triggers it on Windows:

```
from brian2 import *
set_device('cpp_standalone')
G = NeuronGroup(10, 'v:1', threshold='v>1', reset='v=0')
S = Synapses(G, G, 'w : boolean', on_pre='v += int(w)')
S.connect()
run(10*ms)
```

Error message is:

```
cl : Command line warning D9002 : ignoring unknown option '/arch:SSE2'
synapses_pre_codeobject.cpp
code_objects/synapses_pre_codeobject.cpp(1055) : error C2440: 'initializing' : cannot convert from 'std::_Vb_reference<std::_Wrap_alloc<std::allocator<char32_t>>> *' to 'bool *const '
        Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\x86_amd64\cl.EXE"' : return code '0x2'
Stop.
```

One of my students found it running linux too, so it's not just a MS oddity. MSVC version is 18, which is 2013 apparently.

**Comment by thesamovar** [comment]
Ah so also it's not that we're using ``vector<bool>`` but that we try to cast a pointer into ``vector<char32_t>`` to ``bool *``.

**Comment by mstimberg** [comment]
I had a closer look at the issue and realized that while we fixed the use of boolean synaptic variables in #319, we re-introduced the problems with #588 to get around performance problems when always using `char` instead of `bool`. Unfortunately, our test suite only tests *storing* synaptic boolean variables, not actually *using* them...

If I understand correctly why we did the #588 changes, it had to do with boolean expressions that we pulled out of loops. So maybe a reasonable fix to make sure this still works while at the same time allowing for the use of synaptic boolean variables is to give the `c_data_type` function an additional argument and have it return `char` for boolean variables used in dynamic arrays and `bool` otherwise. I *think* this should fix this issue while not affecting the performance in any way. It should also be easy to implement. Thoughts?

**Comment by thesamovar** [comment]
So I reread those threads and it's a complicated story! My impression was that we introduced using bool instead of char to solve a problem, but that later we added the if statements into generated code making the use of bool redundant. In other words, I think we could switch back to just using char with no loss of performance?

**Comment by mstimberg** [comment]
> In other words, I think we could switch back to just using char with no loss of performance?

Hah, maybe -- I'll try and report back with the performance. Having booleans would of course still be advantageous in terms of memory use, but there are probably other improvements that we could do in that regard that require less complicated code.

**Comment by mstimberg** [comment]
Oops, I commited the `bool`->`char` change directly to master by accident... I did a few quick tests and didn't see any noticeable performance regression. I think in the long run we might replace the use of `std::vector` by our own dynamic array implementation (which would reduce the difference between weave and C++ standalone code), adding bool support would then come for free (but of course not change anything about the memory usage, since we'd store a simple `bool` array which takes up one byte per bool).
Let me know if I should revert the commit and do a proper pull request :)

**Comment by thesamovar** [comment]
The change looks fine. Did you test on the CUBA example? That one showed a huge difference for this change previously.

**Comment by thesamovar** [comment]
Also did you run all the long/standalone tests with this just to be sure?

**Comment by mstimberg** [comment]
> Did you test on the CUBA example? That one showed a huge difference for this change previously.

Yep, I did.

> Also did you run all the long/standalone tests with this just to be sure?

Did that as well, did not see any issue on my machine.

**Comment by thesamovar** [comment]
OK, no problem then. :)
