### ISSUE TITLE
Drop-in Numpy Replacements for Backend?

### ISSUE THREAD

**Issue by wenkesj** [brian-team/brian2#891]
I'm fairly certain most people in the Python community are interested in improving `numpy` performance for specific tasks without having to replace code. Is it possible to use a drop-in replacement of the common 'numpy' backend as such:

```python
# prefs.codegen.target = 'numpy'
prefs.codegen.target = 'cupy'
```

I'm using a reference to [CuPy]( https://github.com/cupy/cupy) because I would like to see if this could be possible for this framework when working with large arrays/networks.

Any help would be appreciated! I love this framework, I'm using it for my masters thesis!

**Comment by thesamovar** [comment]
I don't know cupy but if it has the same API as numpy this should be extremely easy to implement. I guess it should be easy as looking at the generated code for the numpy target and replacing all instances of the string numpy with cupy. If you're interested in working on that, let us know and we can give you some pointers.

**Comment by wenkesj** [comment]
@thesamovar yeah that would be nice, it would be interesting to see if it would be possible or plausible even with memory allocated on the GPU. There are also a few other factors haha

**Comment by thesamovar** [comment]
OK I just looked at cupy - hadn't realised it was on GPU. I suspect that it will be more difficult than I said. The reason is that we use some C++ code as well as numpy for a critical operation: propagating spikes. This code is CPU-specific and doesn't use numpy, so you'd have to either (a) copy memory back and forth from CPU to GPU, which will be very slow and likely eliminate any benefit, or (b) rewrite this for GPU, which is very much not straightforward. If you're interested in using the GPU, I'd recommend looking at two existing projects, brian2genn which is released already (https://github.com/brian-team/brian2genn), and brian2cuda which is I think in a pretty good state but not entirely finished (https://github.com/brian-team/brian2cuda). I think at the moment brian2cuda supports more features, but possibly brian2genn is more efficient for the features it does support, but I'm not 100% sure of that.

**Comment by wenkesj** [comment]
Ah, I see. I will look more into what you suggested and possibly look at the internals myself in my spare time.

Thanks for the lightning fast response @thesamovar
