### ISSUE TITLE
numpy 1.14 support?

### ISSUE THREAD

**Issue by RinaldoB** [brian-team/brian2#940]
I ran into this when trying to install brian2 into my anaconda environment. 

I there a reason why numpy 1.13 is required?

To prevent downgrading numpy to 1.13 I ended up installing the dependencies manually and then `conda install brian2 --no-deps`. This is not a good solution but allows me to run Brian2 with numpy 1.14.

As a side now, I imagine using [conda-forge](https://conda-forge.org/#about)  might make conda packaging and dependency management more user friendly in the long-term.

**Comment by mstimberg** [comment]
Hi Rinaldo, sorry for the late reply. We tied Brian packages to specific numpy versions because I erroneously thought this was necessary for our compiled Cython extension (the "spike queue") to work correctly. As discussed [here](https://github.com/brian-team/brian2/pull/913#issuecomment-360494739), we don't actually need to do this as extensions compiled against older numpy versions are compatible with code against newer versions (but not the other way round). The implementation of this was a bit delayed because of a variety of annoying small issues (and my vacation ;) ), but it is ongoing and should be merged soon, see PR #954.

About conda-forge: I agree, see #956. Note that building Brian on conda-forge only became possible about a year ago when I added two of Brian's dependencies (`py-cpuinfo` and `weave`) to conda-forge.

**Comment by thesamovar** [comment]
This is now covered in other issues, so closing (but feel free to reopen if there is still something not covered).
