### ISSUE TITLE
NeuronGroup eqn: each neuron dependent on pre-synaptic neuron equation?

### ISSUE THREAD

**Issue by evearmstrong** [brian-team/brian2#946]
Hi - Thank you for distributing Brian2.  I am struggling to code a network of Hodgkin-Huxley neurons where the synapse gating variables depends on pre-synaptic voltage at each time step, regardless of spiking.  That is:
dV_post/dt = sum(I_ionchannels) + sum(I_syn) + I_applied,
where:
I_syn = gmax * s * (Erev - V_post).
Here, s is the synapse gating variable for the post-synaptic cell, which depends on V_pre:
ds/dt = alpha * GABAmax / (1.0 + exp(-(V_pre - C1)/C2)) * (1. - s) - beta*s.
Within the framework of Brian2, it appears that: i) neuron equations will not accept "_pre" notation, and ii) synapse equations will not refer back to neuron equations.  How do I write this into your architecture? 

Thanks so much,
eve - aeve@sas.upenn.edu

**Comment by mstimberg** [comment]
Hi. In Brian, you express this using a "summed variable". Please have a look at the documentation, its example is quite similar to what you have in mind: http://brian2.readthedocs.io/en/stable/user/synapses.html#summed-variables

PS: These kind of questions are better asked on our [mailing list](http://groups.google.com/group/briansupport) instead of as an issue on github (see http://brian2.readthedocs.io/en/stable/introduction/support.html)

**Comment by evearmstrong** [comment]
Thank you.
