### ISSUE TITLE
Why is the threshold of Poisson neuron equal to 'rand() < rates * dt'?

### ISSUE THREAD

**Issue by efremale** [brian-team/brian2#992]
As stated in the docs in the section "Setting rates for Poisson inputs" (
https://brian2.readthedocs.io/en/stable/user/input.html), the probability or Poisson neuron firing at a given time step is 'rates * dt'.

Shouldn't it be '1 - exp(-rates*dt)' from the definition of Poisson distribution?
How can the former make sense if the rate is high enough and 'rates * dt > 1'?

**Comment by mstimberg** [comment]
Hi, please ask general questions on the mailing list (http://groups.google.com/group/briansupport or briansupport@googlegroups.com) -- issues should be reserved for bugs or feature requests.

> Shouldn't it be '1 - exp(-rates*dt)' from the definition of Poisson distribution?

No, a Poisson neuron is a Poisson point process. Using `rates*dt` as the probability for firing a spike within the interval `dt` will lead to a number of spikes that is Poisson distributed over larger intervals.

> How can the former make sense if the rate is high enough and 'rates * dt > 1'?

It does not, that's why we state in the [documentation](https://brian2.readthedocs.io/en/stable/user/input.html#more-on-poisson-inputs):
> Note that, as can be seen in its equivalent `NeuronGroup` formulation, a `PoissonGroup` does not work for high rates where more than one spike might fall into a single timestep. Use several units with lower rates in this case (e.g. use `PoissonGroup(10, 1000*Hz)` instead of `PoissonGroup(1, 10000*Hz)`).
